In [10]:
import pandas as pd
import os

In [11]:
df = pd.read_csv("pg_scripts/data.csv")

df

,id,address_state,application_type,emp_length,emp_title,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,...,sub_grade,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
0,1077430,GA,INDIVIDUAL,< 1 year,Ryder,C,RENT,11-02-2021,13-09-2021,13-04-2021,...,C4,60 months,Source Verified,30000.0,0.0100,59.83,0.1527,2500,4,1009
1,1072053,CA,INDIVIDUAL,9 years,MKC Accounting,E,RENT,01-01-2021,14-12-2021,15-01-2021,...,E1,36 months,Source Verified,48000.0,0.0535,109.43,0.1864,3000,4,3939
2,1069243,CA,INDIVIDUAL,4 years,Chemat Technology Inc,C,RENT,05-01-2021,12-12-2021,09-01-2021,...,C5,36 months,Not Verified,50000.0,0.2088,421.65,0.1596,12000,11,3522
3,1041756,TX,INDIVIDUAL,< 1 year,barnes distribution,B,MORTGAGE,25-02-2021,12-12-2021,12-03-2021,...,B2,60 months,Source Verified,42000.0,0.0540,97.06,0.1065,4500,9,4911
4,1068350,IL,INDIVIDUAL,10+ years,J&J Steel Inc,A,MORTGAGE,01-01-2021,14-12-2021,15-01-2021,...,A1,36 months,Verified,83000.0,0.0231,106.53,0.0603,3500,28,3835
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38571,803452,NJ,INDIVIDUAL,< 1 year,Joseph M Sanzari Company,C,MORTGAGE,11-07-2021,16-05-2021,16-05-2021,...,C1,60 months,Verified,100000.0,0.1986,551.64,0.1299,24250,33,31946
38572,970377,NY,INDIVIDUAL,8 years,Swat Fame,C,RENT,11-10-2021,16-04-2021,16-05-2021,...,C1,60 months,Verified,50000.0,0.0458,579.72,0.1349,25200,18,31870
38573,875376,CA,INDIVIDUAL,5 years,Anaheim Regional Medical Center,D,RENT,11-09-2021,16-05-2021,16-05-2021,...,D5,60 months,Verified,65000.0,0.1734,627.93,0.1749,25000,20,35721
38574,972997,NY,INDIVIDUAL,5 years,Brooklyn Radiology,D,RENT,11-10-2021,16-05-2021,16-05-2021,...,D5,60 months,Verified,368000.0,0.0009,612.72,0.1825,24000,9,33677
38575,682952,NY,INDIVIDUAL,4 years,Allen Edmonds,F,RENT,11-07-2021,16-05-2021,16-05-2021,...,F3,60 months,Verified,80000.0,0.0600,486.86,0.2099,18000,7,27679

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38576 entries, 0 to 38575
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     38576 non-null  int64
 1   address_state          38576 non-null  object
 2   application_type       38576 non-null  object
 3   emp_length             38576 non-null  object
 4   emp_title              37138 non-null  object
 5   grade                  38576 non-null  object
 6   home_ownership         38576 non-null  object
 7   issue_date             38576 non-null  object
 8   last_credit_pull_date  38576 non-null  object
 9   last_payment_date      38576 non-null  object
 10  loan_status            38576 non-null  object
 11  next_payment_date      38576 non-null  object
 12  member_id              38576 non-null  int64
 13  purpose                38576 non-null  object
 14  sub_grade              38576 non-null  object
 15  term                   38576 non-null  object
 16  verification_status    38576 non-null  object
 17  annual_income          38576 non-null  float64
 18  dti                    38576 non-null  float64
 19  installment            38576 non-null  float64
 20  int_rate               38576 non-null  float64
 21  loan_amount            38576 non-null  int64
 22  total_acc              38576 non-null  int64
 23  total_payment          38576 non-null  int64
dtypes: float64(4), int64(5), object(15)
memory usage: 7.1+ MB

In [13]:
df.describe()

,id,member_id,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
count,3.857600e+04,3.857600e+04,3.857600e+04,38576.000000,38576.000000,38576.000000,38576.000000,38576.000000,38576.000000
mean,6.810371e+05,8.476515e+05,6.964454e+04,0.133274,326.862965,0.120488,11296.066855,22.132544,12263.348533
std,2.113246e+05,2.668105e+05,6.429368e+04,0.066662,209.092000,0.037164,7460.746022,11.392282,9051.104777
min,5.473400e+04,7.069900e+04,4.000000e+03,0.000000,15.690000,0.054200,500.000000,2.000000,34.000000
25%,5.135170e+05,6.629788e+05,4.150000e+04,0.082100,168.450000,0.093200,5500.000000,14.000000,5633.000000
50%,6.627280e+05,8.473565e+05,6.000000e+04,0.134200,283.045000,0.118600,10000.000000,20.000000,10042.000000
75%,8.365060e+05,1.045652e+06,8.320050e+04,0.185900,434.442500,0.145900,15000.000000,29.000000,16658.000000
max,1.077501e+06,1.314167e+06,6.000000e+06,0.299900,1305.190000,0.245900,35000.000000,90.000000,58564.000000

In [14]:
df.nunique()

id                       38576
address_state               50
application_type             1
emp_length                  11
emp_title                28525
grade                        7
home_ownership               5
issue_date                  65
last_credit_pull_date      107
last_payment_date          102
loan_status                  3
next_payment_date          102
member_id                38576
purpose                     14
sub_grade                   35
term                         2
verification_status          3
annual_income             5096
dti                       2863
installment              15132
int_rate                   371
loan_amount                880
total_acc                   82
total_payment            19525
dtype: int64

In [16]:
# Count null values per column
null_counts = df.isnull().sum()
null_counts

id                          0
address_state               0
application_type            0
emp_length                  0
emp_title                1438
grade                       0
home_ownership              0
issue_date                  0
last_credit_pull_date       0
last_payment_date           0
loan_status                 0
next_payment_date           0
member_id                   0
purpose                     0
sub_grade                   0
term                        0
verification_status         0
annual_income               0
dti                         0
installment                 0
int_rate                    0
loan_amount                 0
total_acc                   0
total_payment               0
dtype: int64

In [17]:
def unique_values_per_column(df):
    """
    Prints the unique values for each column in a Pandas DataFrame.

    Args:
        df (pd.DataFrame): The input DataFrame.
    """
    for col in df.columns:
        unique_vals = df[col].unique()
        print(f"Column '{col}':")
        print(unique_vals)

unique_values_per_column(df)

Column 'id':
[1077430 1072053 1069243 ...  875376  972997  682952]
Column 'address_state':
['GA' 'CA' 'TX' 'IL' 'PA' 'FL' 'MI' 'RI' 'NY' 'MD' 'WI' 'NV' 'UT' 'WA'
 'NH' 'HI' 'MA' 'OK' 'NJ' 'OH' 'AZ' 'CT' 'MN' 'CO' 'TN' 'VA' 'MO' 'DE'
 'NM' 'LA' 'AR' 'KY' 'NC' 'SC' 'WV' 'KS' 'WY' 'OR' 'AL' 'VT' 'MS' 'DC'
 'MT' 'SD' 'AK' 'IN' 'ME' 'ID' 'NE' 'IA']
Column 'application_type':
['INDIVIDUAL']
Column 'emp_length':
['< 1 year' '9 years' '4 years' '10+ years' '3 years' '5 years' '1 year'
 '6 years' '2 years' '7 years' '8 years']
Column 'emp_title':
['Ryder' 'MKC Accounting' 'Chemat Technology Inc' ...
 'Anaheim Regional Medical Center' 'Brooklyn Radiology' 'Allen Edmonds']
Column 'grade':
['C' 'E' 'B' 'A' 'D' 'F' 'G']
Column 'home_ownership':
['RENT' 'MORTGAGE' 'OWN' 'OTHER' 'NONE']
Column 'issue_date':
['11-02-2021' '01-01-2021' '05-01-2021' '25-02-2021' '17-07-2021'
 '19-11-2021' '11-06-2021' '02-09-2021' '09-02-2021' '22-07-2021'
 '11-09-2021' '11-08-2021' '11-12-2021' '11-10-2021' '02-12-2021'
 '09-10-2021' '12-12-2021' '02-02-2021' '07-07-2021' '08-01-2021'
 '09-08-2021' '11-01-2021' '11-11-2021' '09-06-2021' '10-01-2021'
 '11-05-2021' '10-03-2021' '10-05-2021' '09-05-2021' '11-04-2021'
 '09-07-2021' '09-12-2021' '09-11-2021' '09-03-2021' '08-10-2021'
 '08-03-2021' '08-11-2021' '07-09-2021' '08-02-2021' '07-08-2021'
 '09-01-2021' '10-12-2021' '11-03-2021' '10-07-2021' '11-07-2021'
 '09-04-2021' '10-02-2021' '10-08-2021' '10-04-2021' '10-11-2021'
 '10-10-2021' '10-06-2021' '09-09-2021' '08-08-2021' '10-09-2021'
 '08-12-2021' '08-05-2021' '08-06-2021' '08-09-2021' '08-07-2021'
 '08-04-2021' '07-11-2021' '07-10-2021' '07-12-2021' '07-06-2021']
Column 'last_credit_pull_date':
['13-09-2021' '14-12-2021' '12-12-2021' '16-03-2021' '14-06-2021'
 '14-07-2021' '15-06-2021' '13-03-2021' '13-10-2021' '14-02-2021'
 '16-04-2021' '15-09-2021' '16-05-2021' '09-12-2021' '13-02-2021'
 '13-11-2021' '10-11-2021' '14-04-2021' '12-01-2021' '12-03-2021'
 '11-06-2021' '13-12-2021' '12-06-2021' '14-03-2021' '11-04-2021'
 '11-11-2021' '15-02-2021' '11-07-2021' '10-12-2021' '11-01-2021'
 '07-08-2021' '10-05-2021' '12-09-2021' '10-09-2021' '10-02-2021'
 '11-03-2021' '16-02-2021' '12-05-2021' '11-02-2021' '14-10-2021'
 '14-01-2021' '11-09-2021' '14-11-2021' '14-09-2021' '15-12-2021'
 '12-11-2021' '15-11-2021' '14-08-2021' '15-07-2021' '11-12-2021'
 '15-10-2021' '13-08-2021' '10-03-2021' '11-08-2021' '16-01-2021'
 '13-07-2021' '13-04-2021' '14-05-2021' '13-05-2021' '15-05-2021'
 '12-08-2021' '15-01-2021' '11-05-2021' '15-04-2021' '12-10-2021'
 '11-10-2021' '15-08-2021' '12-02-2021' '10-04-2021' '13-06-2021'
 '09-02-2021' '08-12-2021' '15-03-2021' '12-04-2021' '12-07-2021'
 '13-01-2021' '10-07-2021' '10-10-2021' '09-09-2021' '10-06-2021'
 '10-08-2021' '09-11-2021' '09-10-2021' '07-06-2021' '09-06-2021'
 '07-12-2021' '09-08-2021' '09-01-2021' '09-03-2021' '08-08-2021'
 '10-01-2021' '09-05-2021' '08-10-2021' '08-09-2021' '08-02-2021'
 '08-01-2021' '09-04-2021' '07-10-2021' '09-07-2021' '08-05-2021'
 '08-03-2021' '07-05-2021' '08-07-2021' '07-09-2021' '20-01-2022'
 '08-06-2021' '07-07-2021']
Column 'last_payment_date':
['13-04-2021' '15-01-2021' '09-01-2021' '12-03-2021' '12-08-2021'
 '13-12-2021' '14-07-2021' '12-10-2021' '16-03-2021' '13-08-2021'
 '13-09-2021' '14-12-2021' '13-10-2021' '12-11-2021' '15-02-2021'
 '10-08-2021' '10-02-2021' '11-06-2021' '08-08-2021' '13-06-2021'
 '09-12-2021' '12-02-2021' '12-07-2021' '10-07-2021' '13-01-2021'
 '11-08-2021' '11-10-2021' '11-01-2021' '13-07-2021' '09-10-2021'
 '13-11-2021' '10-11-2021' '11-03-2021' '11-07-2021' '12-06-2021'
 '11-12-2021' '09-09-2021' '13-05-2021' '14-03-2021' '08-04-2021'
 '10-10-2021' '10-05-2021' '11-02-2021' '10-09-2021' '10-04-2021'
 '10-06-2021' '12-05-2021' '14-10-2021' '14-06-2021' '14-05-2021'
 '14-01-2021' '14-04-2021' '11-09-2021' '14-08-2021' '14-11-2021'
 '12-01-2021' '14-02-2021' '12-12-2021' '12-04-2021' '13-02-2021'
 '14-09-2021' '10-03-2021' '11-11-2021' '11-04-2021' '13-03-2021'
 '11-05-2021' '09-11-2021' '12-09-2021' '09-02-2021' '08-12-2021'
 '10-12-2021' '09-07-2021' '10-01-2021' '09-06-2021' '15-04-2021'
 '15-03-2021' '16-02-2021' '15-05-2021' '16-05-2021' '15-11-2021'
 '16-04-2021' '15-06-2021' '15-10-2021' '15-09-2021' '15-07-2021'
 '16-01-2021' '15-12-2021' '15-08-2021' '16-06-2021' '09-05-2021'
 '08-10-2021' '09-08-2021' '09-04-2021' '08-05-2021' '09-03-2021'
 '08-09-2021' '08-11-2021' '08-07-2021' '08-06-2021' '08-03-2021'
 '08-02-2021' '08-01-2021']
Column 'loan_status':
['Charged Off' 'Fully Paid' 'Current']
Column 'next_payment_date':
['13-05-2021' '15-02-2021' '09-02-2021' '12-04-2021' '12-09-2021'
 '13-01-2022' '14-08-2021' '12-11-2021' '16-04-2021' '13-09-2021'
 '13-10-2021' '14-01-2022' '13-11-2021' '12-12-2021' '15-03-2021'
 '10-09-2021' '10-03-2021' '11-07-2021' '08-09-2021' '13-07-2021'
 '09-01-2022' '12-03-2021' '12-08-2021' '10-08-2021' '13-02-2021'
 '11-09-2021' '11-11-2021' '11-02-2021' '13-08-2021' '09-11-2021'
 '13-12-2021' '10-12-2021' '11-04-2021' '11-08-2021' '12-07-2021'
 '11-01-2022' '09-10-2021' '13-06-2021' '14-04-2021' '08-05-2021'
 '10-11-2021' '10-06-2021' '11-03-2021' '10-10-2021' '10-05-2021'
 '10-07-2021' '12-06-2021' '14-11-2021' '14-07-2021' '14-06-2021'
 '14-02-2021' '14-05-2021' '11-10-2021' '14-09-2021' '14-12-2021'
 '12-02-2021' '14-03-2021' '12-01-2022' '12-05-2021' '13-03-2021'
 '14-10-2021' '10-04-2021' '11-12-2021' '11-05-2021' '13-04-2021'
 '11-06-2021' '09-12-2021' '12-10-2021' '09-03-2021' '08-01-2022'
 '10-01-2022' '09-08-2021' '10-02-2021' '09-07-2021' '15-05-2021'
 '15-04-2021' '16-03-2021' '15-06-2021' '16-06-2021' '15-12-2021'
 '16-05-2021' '15-07-2021' '15-11-2021' '15-10-2021' '15-08-2021'
 '16-02-2021' '15-01-2022' '15-09-2021' '16-07-2021' '09-06-2021'
 '08-11-2021' '09-09-2021' '09-05-2021' '08-06-2021' '09-04-2021'
 '08-10-2021' '08-12-2021' '08-08-2021' '08-07-2021' '08-04-2021'
 '08-03-2021' '08-02-2021']
Column 'member_id':
[1314167 1288686 1304116 ... 1089898 1194971  872217]
Column 'purpose':
['car' 'credit card' 'Debt consolidation' 'educational' 'home improvement'
 'house' 'major purchase' 'medical' 'moving' 'other' 'renewable_energy'
 'small business' 'vacation' 'wedding']
Column 'sub_grade':
['C4' 'E1' 'C5' 'B2' 'A1' 'C3' 'C2' 'A4' 'A5' 'B5' 'B4' 'B3' 'B1' 'D1'
 'A2' 'A3' 'D4' 'D2' 'C1' 'D3' 'E3' 'F1' 'E2' 'E5' 'D5' 'E4' 'F2' 'G3'
 'F3' 'G1' 'F4' 'G4' 'G2' 'F5' 'G5']
Column 'term':
[' 60 months' ' 36 months']
Column 'verification_status':
['Source Verified' 'Not Verified' 'Verified']
Column 'annual_income':
[ 30000.   48000.   50000.  ...  44250.   57040.5 368000. ]
Column 'dti':
[0.01   0.0535 0.2088 ... 0.2721 0.2543 0.272 ]
Column 'installment':
[ 59.83 109.43 421.65 ... 164.99 113.5  627.93]
Column 'int_rate':
[0.1527 0.1864 0.1596 0.1065 0.0603 0.1465 0.1427 0.079  0.089  0.1269
 0.1242 0.1171 0.0991 0.1629 0.0743 0.1114 0.1109 0.0766 0.0751 0.0963
 0.0894 0.1148 0.1149 0.157  0.0788 0.0705 0.1189 0.1074 0.1284 0.0749
 0.0849 0.1136 0.1199 0.1095 0.1099 0.1221 0.1241 0.1134 0.1399 0.1367
 0.1677 0.1    0.0807 0.0863 0.0976 0.1393 0.0712 0.1046 0.092  0.1166
 0.1091 0.1103 0.074  0.0768 0.0662 0.0599 0.0699 0.0729 0.0542 0.0676
 0.0774 0.0692 0.0932 0.0617 0.0639 0.0579 0.08   0.0859 0.0714 0.0691
 0.0737 0.0832 0.0925 0.1075 0.0999 0.1036 0.1025 0.1111 0.1126 0.1218
 0.1059 0.0962 0.1037 0.1158 0.0988 0.1062 0.1253 0.1051 0.1287 0.1273
 0.138  0.1472 0.1347 0.1523 0.1426 0.1268 0.1311 0.1417 0.1349 0.1304
 0.1599 0.1595 0.1533 0.0654 0.1183 0.1357 0.1306 0.1422 0.1316 0.1496
 0.1565 0.1474 0.1505 0.1442 0.1008 0.1033 0.0888 0.1222 0.1323 0.1197
 0.1361 0.1435 0.1398 0.1343 0.1392 0.1348 0.1479 0.1521 0.1292 0.1409
 0.1459 0.1531 0.1558 0.1704 0.1645 0.1719 0.183  0.1632 0.1335 0.1372
 0.1112 0.0742 0.1186 0.1298 0.1299 0.1528 0.1223 0.1379 0.1322 0.1454
 0.1484 0.1649 0.16   0.152  0.1229 0.1774 0.1749 0.1038 0.1491 0.1483
 0.1568 0.1799 0.1163 0.1537 0.1714 0.1727 0.1446 0.1602 0.1969 0.1756
 0.164  0.1261 0.1839 0.1669 0.1825 0.1557 0.1682 0.1867 0.2285 0.1929
 0.1689 0.1758 0.1788 0.1899 0.2025 0.1751 0.1903 0.2062 0.1966 0.1743
 0.1942 0.2089 0.1991 0.2206 0.203  0.2274 0.2391 0.0838 0.087  0.1122
 0.1249 0.0901 0.1028 0.1154 0.1071 0.1217 0.0964 0.133  0.1236 0.1355
 0.1633 0.1809 0.1538 0.0907 0.1146 0.1083 0.1128 0.0775 0.0996 0.0951
 0.1078 0.1267 0.1387 0.1407 0.1482 0.1583 0.1488 0.0933 0.0945 0.0983
 0.1039 0.1141 0.1172 0.1324 0.1438 0.0938 0.1212 0.102  0.1385 0.1159
 0.1272 0.1611 0.1178 0.1317 0.1562 0.06   0.1286 0.1411 0.1461 0.1739
 0.145  0.2099 0.1384 0.1191 0.1607 0.1412 0.1418 0.1879 0.1913 0.1821
 0.2017 0.0791 0.1209 0.2174 0.1462 0.1746 0.1979 0.1941 0.1096 0.1635
 0.1663 0.1853 0.1862 0.2127 0.2086 0.2069 0.1254 0.1726 0.1817 0.1974
 0.2211 0.1706 0.1793 0.1936 0.2313 0.2136 0.2235 0.2011 0.2248 0.1854
 0.2122 0.2128 0.2167 0.1807 0.1904 0.178  0.2411 0.2048 0.2016 0.2085
 0.2053 0.2352 0.1375 0.1014 0.1312 0.128  0.1703 0.1615 0.1608 0.2121
 0.1336 0.1493 0.209  0.167  0.1843 0.1715 0.1872 0.1204 0.1362 0.1576
 0.1513 0.1425 0.1467 0.1545 0.1671 0.097  0.1849 0.1588 0.1507 0.1601
 0.1262 0.1064 0.1001 0.0967 0.143  0.1695 0.1947 0.1696 0.1982 0.2114
 0.1659 0.1939 0.2003 0.1525 0.204  0.1878 0.162  0.2322 0.2359 0.2264
 0.2159 0.1891 0.202  0.2294 0.2182 0.2077 0.2164 0.179  0.1475 0.1734
 0.147  0.1744 0.2148 0.2459 0.244  0.1501 0.2052 0.1836 0.1916 0.1884
 0.1754]
Column 'loan_amount':
[ 2500  3000 12000  4500  3500  8000  6000  5500 24000  4125  5400 11200
  5000  3050 10000  2225  4000  7000  9000  4800  6300  4750  1850  4200
  7200  2400  7500  5550 22000  3200 11000  4400  8500  2000  7400  5650
  1800  6500 15000  8700  5600  4600  3800 16000  1300  7800  5900  3600
  2100  4975  1925  1500  7750  9600  3900 12975  5950  5100  5200  1200
  4650  1450  3250  3300  1700  5525 18000  1750  5375  9500  7600  6400
  9900  1000 10400 23500 22600 23600 13100  5800 10800  1900  8400  3075
  6200 11500  4350  4150  4900  6125  2425  1600  7100  8900 14000 12250
  3700 17000  2550  6250 14400  8200  9250  3375  1675  8600  2800  3525
  8800  2250  4375  1275  5050 25000  9800  6600  8250  2825  5975  3350
 20000 19000  2200 14750  9575 13250  2350 10625  1400 12800 16800  5750
  8975  5275  5850  2275 14800  5300 20400 16500  2950  6800  6775  9925
  2475  7275 17500  9100  2650 10500 22800  6900 21000 14900  2875  3825
  7875  4625 11900  2900  4250 13000 10200 15950  8100 13200  6100 16675
 12600  6075  9175  5150  5625 12500  8650  8750  7250  5575  4700  2300
  5700 28000  3100 13500 14500 15850 15600 12325  4950 15325  7575 17600
 10750  6275  9975  6700 16600 10600 19200 16200 21600 15500 12450 18500
 13800 30000  4550 10550  9350  6350 32000  5125 12400 25600 20975 11800
 15300  8850 11100 13475 11625 19600  4475 26800 11300  4100 11700 26000
 22500 24500 21400 35000 22400 14575  7125 10375 20050 24925 12375  7150
 17250 13225 11775 16400 10075 20125  6950 23000  4050  1950 21500  9200
  4325 13575  6625 16250  8950 14100 19750  7650  3675  9525 19950  5875
  3975 24625  2675 14275 14300 15450  9300   750  6225 17950 12750 13975
 16075 10675 18650  7900 15875 10475  2325 19150  2700  9075  3125  6575
 11050  3150  3625  9400 10250  7475  3425 20800 15200 10050 18300 13950
  9750 23450 14950 10175  8300 16750 18800  1250 19500 10650  8550 15250
 10700 17525 21125  8150 11600  9700 13600 20500  8575 12900 14700 12700
  2750  7775 12100 10825   725 10950 11250  3725  9050  1375  4450  3400
  6650  6925  1475 10150  6475  4575 17400  2375  6150  2050  2725 18200
  9150  7050 18600  9425  3850  4850  8450  7925  9450 10725  2600  3750
 13300 11550 13650  4300  8350  7950  1150  5925 12350 27250 13750  7350
  8675  7700 25850  1050  2850 17325 14550  1425  6975 12775 12025 11400
 18150 11075 18250 16775  7850  8325 25975 31000  1125  9875  6550  8775
  2450  6750  9950  4025  6850  1350 11450 10300 17700 11975 18225  4675
  4925 19400 17475  6025 15700 21250  2150 11525 23750 17200 22950 17750
  5475 14600  1875 19650 13275  7450 19550  7675 15175  9275 23100 16300
 10875 13700 23700 22100 12200 12875 16700 10850  5250 13125  5225  9125
 16950 12725 26375 27400  4775 34000 17800 33250 17050 19800 18400 23325
 25475 12300 29000 24375 27500  8175 18550 14250 16875  7300 27600  3450
  6325  3650 15050  5825 24250 17625 20900 15625 15400 19125 14475  8050
 10225  8875  1825 23575 30600  8125 13400 12550  9550 15350 33500 11850
 16450  4275 26300 15075  9325 14125 12650  8075 26850 29700 21725 24575
 31500 22250 30800  6450 17850 20675 30750 10975 22750 21225 27000 15900
 33425 19700 18950 31300 27300 28600 24600 23200 17150 12675 25450 14875
 25900 28100 21850 23975 31825 26500 17100 21200 30400 25875 20250 17675
 16425 18825  6375  7325 13350 22475 29500 11875 15550 16100 10525 19775
 22200 27050 28625 27575 19075 11225  8525 10325 19275  7725  8275 10275
  7025  5175  5075  8475 14975  5425 19900  7550 10100   800 12125 13025
 22550  5450 17350 24750  2975  4225  2925 13450  7375  3275  5325 14825
  6825  3950  1525 11650 11325 13675  7975  3225 13075 18050 12150 24800
 14200 14675 20600 11425 11275 11125 10125 24150 15275 20700 13050  6425
 17875 10900  9225  9475  6675  4175  3550  8725 15800  3775 15750  7525
  7075 22650 10025 14850 11575  4075  1775  8625  2775  4725  8225  5775
 11025 11750 13900 14150 15775  4875  2525 31050 16525   700 10450 13425
 11175  1550  4425 13150  9850 12625  6725  8025  5350 33000 18725  9375
  3325  3025  9775 18325 10575  5025 14650 24400  7425 18750 12225 23275
 14075  3575 10925  2125 14625 23050 12275 15825 28250 15150 32400  7225
 15675 14525 14725 12075  8825  1325 10425 24175  5725  1625 26400  9725
 17725 13775  2575 13375 23525 33950 17450 12925 21100 19725 21825 16725
 23800 21650 19450 14350  9625 20475 18125 27175 29800 23400 20375 29550
 17975 21450 17900 19425 19850 13625 15125 21700 32500 23475 10775 15575
 11475 20200 29850 23850 29100 12950 16050 34800  7175 18900 11725  9650
 13550 12175  8375 14175 11675 33600 15425 12050  1100 12825 23350 19575
 13725 10350 28800 16225 16550 31150 23075 17275 26025  4525 25500 12425
  1650 21575 20950 22125 22325 26250 32350 25200 21750 19300 34475 20300
 24650 20450 31200 21425 28200 22900 18975 17425 28750 34525 21350 23675
 34675 22875 19250 18275 29900 21300 19875 17075 32775 32875 23425 32250
 18875 31725 29375 22575 21625 16350 13325 25375 27525 31325 14225 16275
 27200 18575 29175 28500 30500 24700 31025 17225 31700 26200  3875 32275
   900 22350 11375 12475 13175 24200 19925 17375 16325 11350 32525 30100
 29275  7625 13850 15650 17300 17175 21800 31800 14050 24100  5675  1075
  3925  3475 29300  2625  2075  3175 19975   500   950 20150 15975  6525
 17925 12850 22300  6175  6875 25300 15025 31400  9825 19475 25400 30225
 34200 27700 17825 24975]
Column 'total_acc':
[ 4 11  9 28 30 23 31 21 33 13  3 15 18 14  8  7 20 39 24 10 19 27  6 16
 45 25  5 43 29 22 41 35 44 36 17 26 37 32 47 52 42 46 12 50 34 59 38 63
 49 48 61 51 55 40 53 62 58 67 54 57 56 70  2 64 60 80 79 71 66 65 69 90
 68 74 75 87 78 72 77 81 76 73]
Column 'total_payment':
[ 1009  3939  3522 ... 31870 35721 33677]