## Exploratory Data Analysis

### Import Libraries

In [1]:
import sys
import polars as pl
import polars.selectors as pol_sel

### Show Python & Library Versions

In [2]:
l = 8
r = 12

print("Python".rjust(l), ":", sys.version[0:6].ljust(r))
print("Polars".rjust(l), ":", pl.__version__.ljust(r))

  Python : 3.11.4
  Polars : 1.12.0

### Load CSV File into Polars DataFrame

In [3]:
df = pl.read_csv("data/cars-dataset.csv")

df

shape: (29_792, 56)
┌───────┬───────────────┬────────┬─────────┬───┬─────────┬───────────────┬──────────┬──────────────┐
│       ┆ Model         ┆ Serie  ┆ Company ┆ … ┆ Low mpg ┆ Total maximum ┆ Maximum  ┆ Specificatio │
│ ---   ┆ ---           ┆ ---    ┆ ---     ┆   ┆ ---     ┆ torque        ┆ Capacity ┆ n summary    │
│ i64   ┆ str           ┆ str    ┆ str     ┆   ┆ str     ┆ ---           ┆ ---      ┆ ---          │
│       ┆               ┆        ┆         ┆   ┆         ┆ str           ┆ str      ┆ str          │
╞═══════╪═══════════════╪════════╪═════════╪═══╪═════════╪═══════════════╪══════════╪══════════════╡
│ 0     ┆ AC Ace        ┆ Ace    ┆ AC      ┆ … ┆ null    ┆ null          ┆ null     ┆ 4.9L V8 4AT  │
│       ┆ (1993-1996)   ┆        ┆         ┆   ┆         ┆               ┆          ┆ (260 HP)     │
│ 1     ┆ AC Aceca      ┆ Aceca  ┆ AC      ┆ … ┆ null    ┆ null          ┆ null     ┆ 3.5L V8 32V  │
│       ┆ (1998-2000)   ┆        ┆         ┆   ┆         ┆               ┆          ┆ Turbo 6MT    │
│       ┆               ┆        ┆         ┆   ┆         ┆               ┆          ┆ (354 HP)     │
│ 2     ┆ AC Aceca      ┆ Aceca  ┆ AC      ┆ … ┆ null    ┆ null          ┆ null     ┆ 4.6L V8 5MT  │
│       ┆ (1998-2000)   ┆        ┆         ┆   ┆         ┆               ┆          ┆ (326 HP)     │
│ 3     ┆ AC Cobra      ┆ Cobra  ┆ AC      ┆ … ┆ null    ┆ null          ┆ null     ┆ 4.7L V8 4MT  │
│       ┆ MkIII         ┆        ┆         ┆   ┆         ┆               ┆          ┆ (280 HP)     │
│       ┆ (1965-1967)   ┆        ┆         ┆   ┆         ┆               ┆          ┆              │
│ 4     ┆ AC Cobra 378  ┆ Cobra  ┆ AC      ┆ … ┆ null    ┆ null          ┆ null     ┆ 6.2L V8 6MT  │
│       ┆ MkIV          ┆        ┆         ┆   ┆         ┆               ┆          ┆              │
│       ┆ (1965-1967)   ┆        ┆         ┆   ┆         ┆               ┆          ┆              │
│ …     ┆ …             ┆ …      ┆ …       ┆ … ┆ …       ┆ …             ┆ …        ┆ …            │
│ 29787 ┆ 2026 Zenvo    ┆ Aurora ┆ Zenvo   ┆ … ┆ null    ┆ 1032.6 lb-ft  ┆ null     ┆ 6.6L V12 7AT │
│       ┆ Aurora Agil   ┆        ┆         ┆   ┆         ┆ (1400 Nm)     ┆          ┆ RWD (1471    │
│       ┆               ┆        ┆         ┆   ┆         ┆               ┆          ┆ HP)          │
│ 29788 ┆ 2026 Zenvo    ┆ Aurora ┆ Zenvo   ┆ … ┆ null    ┆ 1253.9 lb-ft  ┆ null     ┆ 6.6L V12 7AT │
│       ┆ Aurora Tur    ┆        ┆         ┆   ┆         ┆ (1700 Nm)     ┆          ┆ AWD (1876    │
│       ┆               ┆        ┆         ┆   ┆         ┆               ┆          ┆ HP)          │
│ 29789 ┆ Zenvo TS1 (20 ┆ TS1    ┆ Zenvo   ┆ … ┆ null    ┆ null          ┆ null     ┆ 5.8 V8 7AT   │
│       ┆ 17-Present)   ┆        ┆         ┆   ┆         ┆               ┆          ┆ (1118 HP)    │
│ 29790 ┆ Zenvo TSR-S   ┆ TSR-S  ┆ Zenvo   ┆ … ┆ null    ┆ null          ┆ null     ┆ 5.8L V8 7AT  │
│       ┆ (2018-Present ┆        ┆         ┆   ┆         ┆               ┆          ┆ (1177 HP)    │
│       ┆ )             ┆        ┆         ┆   ┆         ┆               ┆          ┆              │
│ 29791 ┆ Zenvo ST1     ┆ ST1    ┆ Zenvo   ┆ … ┆ null    ┆ null          ┆ null     ┆ 6.8 V8 7AT   │
│       ┆ (2009-2017)   ┆        ┆         ┆   ┆         ┆               ┆          ┆ (1104 HP)    │
└───────┴───────────────┴────────┴─────────┴───┴─────────┴───────────────┴──────────┴──────────────┘

### Display First Few Rows to Understand Structure of Data

In [4]:
print(df.head())

shape: (5, 56)
┌─────┬───────────────────┬───────┬─────────┬───┬─────────┬─────────┬──────────┬───────────────────┐
│     ┆ Model             ┆ Serie ┆ Company ┆ … ┆ Low mpg ┆ Total   ┆ Maximum  ┆ Specification     │
│ --- ┆ ---               ┆ ---   ┆ ---     ┆   ┆ ---     ┆ maximum ┆ Capacity ┆ summary           │
│ i64 ┆ str               ┆ str   ┆ str     ┆   ┆ str     ┆ torque  ┆ ---      ┆ ---               │
│     ┆                   ┆       ┆         ┆   ┆         ┆ ---     ┆ str      ┆ str               │
│     ┆                   ┆       ┆         ┆   ┆         ┆ str     ┆          ┆                   │
╞═════╪═══════════════════╪═══════╪═════════╪═══╪═════════╪═════════╪══════════╪═══════════════════╡
│ 0   ┆ AC Ace            ┆ Ace   ┆ AC      ┆ … ┆ null    ┆ null    ┆ null     ┆ 4.9L V8 4AT (260  │
│     ┆ (1993-1996)       ┆       ┆         ┆   ┆         ┆         ┆          ┆ HP)               │
│ 1   ┆ AC Aceca          ┆ Aceca ┆ AC      ┆ … ┆ null    ┆ null    ┆ null     ┆ 3.5L V8 32V Turbo │
│     ┆ (1998-2000)       ┆       ┆         ┆   ┆         ┆         ┆          ┆ 6MT (354 HP)      │
│ 2   ┆ AC Aceca          ┆ Aceca ┆ AC      ┆ … ┆ null    ┆ null    ┆ null     ┆ 4.6L V8 5MT (326  │
│     ┆ (1998-2000)       ┆       ┆         ┆   ┆         ┆         ┆          ┆ HP)               │
│ 3   ┆ AC Cobra MkIII    ┆ Cobra ┆ AC      ┆ … ┆ null    ┆ null    ┆ null     ┆ 4.7L V8 4MT (280  │
│     ┆ (1965-1967)       ┆       ┆         ┆   ┆         ┆         ┆          ┆ HP)               │
│ 4   ┆ AC Cobra 378 MkIV ┆ Cobra ┆ AC      ┆ … ┆ null    ┆ null    ┆ null     ┆ 6.2L V8 6MT       │
│     ┆ (1965-1967)       ┆       ┆         ┆   ┆         ┆         ┆          ┆                   │
└─────┴───────────────────┴───────┴─────────┴───┴─────────┴─────────┴──────────┴───────────────────┘

### Retrieve Basic Information About DataFrame

In [5]:
print(df.shape)
print(df.dtypes)

(29792, 56)
[Int64, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String]

### Display Summary Statistics for All Columns

In [6]:
summary = df.describe()
print(summary)

shape: (9, 57)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆           ┆ Model     ┆ Serie     ┆ … ┆ Low mpg   ┆ Total     ┆ Maximum   ┆ Specific │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ maximum   ┆ Capacity  ┆ ation    │
│ str       ┆ f64       ┆ str       ┆ str       ┆   ┆ str       ┆ torque    ┆ ---       ┆ summary  │
│           ┆           ┆           ┆           ┆   ┆           ┆ ---       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 29792.0   ┆ 29792     ┆ 29792     ┆ … ┆ 255       ┆ 396       ┆ 201       ┆ 29792    │
│ null_coun ┆ 0.0       ┆ 0         ┆ 0         ┆ … ┆ 29537     ┆ 29396     ┆ 29591     ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 14895.5   ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ std       ┆ 8600.3539 ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 46        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ min       ┆ 0.0       ┆ 1911      ┆ "Wedge    ┆ … ┆ 10.5 mpg  ┆ 1032.6    ┆ 0.13 kWh  ┆ (136 HP) │
│           ┆           ┆ Bugatti   ┆ Series"   ┆   ┆ US (22.4  ┆ lb-ft     ┆           ┆          │
│           ┆           ┆ Type 19   ┆           ┆   ┆ L/100Km)  ┆ (1400 Nm) ┆           ┆          │
│           ┆           ┆ Bebe      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ 7448.0    ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 50%       ┆ 14896.0   ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 75%       ┆ 22343.0   ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ max       ┆ 29791.0   ┆ Zenvo     ┆ xD        ┆ … ┆ 9.8 mpg   ┆ 995.7     ┆ 98 kWh    ┆ xDriveM5 │
│           ┆           ┆ TSR-S (20 ┆           ┆   ┆ US (24    ┆ lb-ft     ┆           ┆ 0d 8AT   │
│           ┆           ┆ 18-Presen ┆           ┆   ┆ L/100Km)  ┆ (1350 Nm) ┆           ┆ (381 HP) │
│           ┆           ┆ t)        ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Find Longest Text Length in Each Column

In [7]:
# Create an empty list to store max lengths for each string column
longest_text_lengths = []

# Loop through the columns to check for string columns
string_columns = [col for col in df.columns if df[col].dtype == pl.Utf8]

max_lengths = {}
for col in string_columns:
    max_length = df.select(pl.col(col).str.len_chars().max()).to_numpy()[0, 0]
    max_lengths[col] = max_length

df_max_lengths = pl.DataFrame(max_lengths)

df_max_lengths

shape: (1, 55)
┌───────┬───────┬─────────┬────────────┬───┬─────────┬─────────┬──────────┬────────────────────────┐
│ Model ┆ Serie ┆ Company ┆ Body style ┆ … ┆ Low mpg ┆ Total   ┆ Maximum  ┆ Specification summary  │
│ ---   ┆ ---   ┆ ---     ┆ ---        ┆   ┆ ---     ┆ maximum ┆ Capacity ┆ ---                    │
│ u32   ┆ u32   ┆ u32     ┆ u32        ┆   ┆ u32     ┆ torque  ┆ ---      ┆ u32                    │
│       ┆       ┆         ┆            ┆   ┆         ┆ ---     ┆ u32      ┆                        │
│       ┆       ┆         ┆            ┆   ┆         ┆ u32     ┆          ┆                        │
╞═══════╪═══════╪═════════╪════════════╪═══╪═════════╪═════════╪══════════╪════════════════════════╡
│ 82    ┆ 40    ┆ 24      ┆ 65         ┆ … ┆ 26      ┆ 22      ┆ 9        ┆ 58                     │
└───────┴───────┴─────────┴────────────┴───┴─────────┴─────────┴──────────┴────────────────────────┘

### Retrieve Data Types of All Columns

In [8]:
print("Column data types:\n", df.dtypes)

Column data types:
 [Int64, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String]

### Count Unique Values in Each Column

In [9]:
all_columns = [col for col in df.columns]

for col in all_columns:
    unique_counts = df[col].n_unique()
    print(f"Unique values in {col} :".rjust(48), f"{unique_counts}".ljust(6))

                             Unique values in  : 29792
                        Unique values in Model : 7044
                        Unique values in Serie : 2733
                      Unique values in Company : 124
                   Unique values in Body style : 8
                      Unique values in Segment : 28
             Unique values in Production years : 843
                    Unique values in Cylinders : 63
                 Unique values in Displacement : 1305
                    Unique values in Power(HP) : 5335
                   Unique values in Power(BHP) : 5154
                    Unique values in Power(KW) : 6284
                Unique values in Torque(lb-ft) : 5823
                   Unique values in Torque(Nm) : 6194
       Unique values in Electrical motor power : 181
      Unique values in Electrical motor torque : 119
                  Unique values in Fuel System : 322
                         Unique values in Fuel : 13
                Unique values in Fuel capacity : 149
                    Unique values in Top Speed : 528
Unique values in Acceleration 0-62 Mph (0-100 kph) : 285
                   Unique values in Drive Type : 4
                      Unique values in Gearbox : 626
                  Unique values in Front brake : 172
                   Unique values in Rear brake : 164
                    Unique values in Tire Size : 3351
                       Unique values in Length : 999
                        Unique values in Width : 387
                       Unique values in Height : 478
             Unique values in Front/rear Track : 2288
                    Unique values in Wheelbase : 583
             Unique values in Ground Clearance : 188
            Unique values in Aerodynamics (Cd) : 147
  Unique values in Aerodynamics (frontal area) : 39
               Unique values in Turning circle : 91
                 Unique values in Cargo Volume : 612
               Unique values in Unladen Weight : 4348
           Unique values in Gross Weight Limit : 2516
                 Unique values in Combined mpg : 476
                     Unique values in City mpg : 421
                  Unique values in Highway mpg : 369
                Unique values in CO2 Emissions : 757
     Unique values in CO2 Emissions (Combined) : 207
Unique values in Turning circle (curb to curb) : 60
          Unique values in Total maximum power : 220
                   Unique values in Power pack : 28
             Unique values in Nominal Capacity : 162
       Unique values in Top speed (electrical) : 37
                     Unique values in EV Range : 254
                     Unique values in High mpg : 69
               Unique values in Extra high mpg : 74
                   Unique values in Medium mpg : 77
                      Unique values in Low mpg : 93
         Unique values in Total maximum torque : 125
             Unique values in Maximum Capacity : 92
        Unique values in Specification summary : 17676

### Check Distribution of Numerical Columns

In [10]:
numerical_cols = [item for item in all_columns if item not in string_columns]
numerical_cols = [item for item in numerical_cols if item not in ['id']]

numerical_cols

for col in numerical_cols:
    distribution = df.select(col).describe()
    print(col)
    print(distribution, '\n\n')

shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆             │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 29792.0     │
│ null_count ┆ 0.0         │
│ mean       ┆ 14895.5     │
│ std        ┆ 8600.353946 │
│ min        ┆ 0.0         │
│ 25%        ┆ 7448.0      │
│ 50%        ┆ 14896.0     │
│ 75%        ┆ 22343.0     │
│ max        ┆ 29791.0     │
└────────────┴─────────────┘

### Retrieve Null Count For Each Feature

In [15]:
def count_nulls(df: pl.DataFrame):
    # Create a dictionary of column names and their null count
    null_counts = {col: df[col].is_null().sum() for col in df.columns}
    
    # Convert dictionary to a DataFrame for better readability
    result = pl.DataFrame({
        "Column": list(null_counts.keys()),
        "Null Count": list(null_counts.values())
    })
    
    return result


pl.Config.set_tbl_rows(60)

count_nulls(df)

shape: (56, 2)
┌─────────────────────────────────┬────────────┐
│ Column                          ┆ Null Count │
│ ---                             ┆ ---        │
│ str                             ┆ i64        │
╞═════════════════════════════════╪════════════╡
│                                 ┆ 0          │
│ Model                           ┆ 0          │
│ Serie                           ┆ 0          │
│ Company                         ┆ 0          │
│ Body style                      ┆ 7554       │
│ Segment                         ┆ 0          │
│ Production years                ┆ 0          │
│ Cylinders                       ┆ 522        │
│ Displacement                    ┆ 996        │
│ Power(HP)                       ┆ 566        │
│ Power(BHP)                      ┆ 566        │
│ Power(KW)                       ┆ 566        │
│ Torque(lb-ft)                   ┆ 1072       │
│ Torque(Nm)                      ┆ 1072       │
│ Electrical motor power          ┆ 29059      │
│ Electrical motor torque         ┆ 29271      │
│ Fuel System                     ┆ 212        │
│ Fuel                            ┆ 65         │
│ Fuel capacity                   ┆ 8199       │
│ Top Speed                       ┆ 4433       │
│ Acceleration 0-62 Mph (0-100 k… ┆ 5125       │
│ Drive Type                      ┆ 165        │
│ Gearbox                         ┆ 459        │
│ Front brake                     ┆ 309        │
│ Rear brake                      ┆ 320        │
│ Tire Size                       ┆ 2223       │
│ Length                          ┆ 746        │
│ Width                           ┆ 731        │
│ Height                          ┆ 873        │
│ Front/rear Track                ┆ 1990       │
│ Wheelbase                       ┆ 795        │
│ Ground Clearance                ┆ 6486       │
│ Aerodynamics (Cd)               ┆ 8811       │
│ Aerodynamics (frontal area)     ┆ 29637      │
│ Turning circle                  ┆ 26982      │
│ Cargo Volume                    ┆ 3479       │
│ Unladen Weight                  ┆ 2312       │
│ Gross Weight Limit              ┆ 5453       │
│ Combined mpg                    ┆ 4296       │
│ City mpg                        ┆ 7649       │
│ Highway mpg                     ┆ 7664       │
│ CO2 Emissions                   ┆ 9141       │
│ CO2 Emissions (Combined)        ┆ 29090      │
│ Turning circle (curb to curb)   ┆ 29257      │
│ Total maximum power             ┆ 29233      │
│ Power pack                      ┆ 29183      │
│ Nominal Capacity                ┆ 29314      │
│ Top speed (electrical)          ┆ 29594      │
│ EV Range                        ┆ 29285      │
│ High mpg                        ┆ 29549      │
│ Extra high mpg                  ┆ 29555      │
│ Medium mpg                      ┆ 29566      │
│ Low mpg                         ┆ 29537      │
│ Total maximum torque            ┆ 29396      │
│ Maximum Capacity                ┆ 29591      │
│ Specification summary           ┆ 0          │
└─────────────────────────────────┴────────────┘