## Exploratory Data Analysis

### Import Libraries

In [1]:
import sys
import polars as pl
import polars.selectors as pol_sel

### Show Python & Library Versions

In [2]:
l = 8
r = 12

print("Python".rjust(l), ":", sys.version[0:6].ljust(r))
print("Polars".rjust(l), ":", pl.__version__.ljust(r))

  Python : 3.11.4
  Polars : 1.12.0

### Load CSV File into Polars DataFrame

In [5]:
df = pl.read_csv("mongodb_scripts/data.csv")

df

shape: (7_991, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ order_num ┆ sales_cha ┆ warehouse ┆ procured_ ┆ … ┆ order_qua ┆ discount_ ┆ unit_cost ┆ unit_pri │
│ ber       ┆ nnel      ┆ _code     ┆ date      ┆   ┆ ntity     ┆ applied   ┆ ---       ┆ ce       │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ i64       ┆ f64       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ SO -      ┆ In-Store  ┆ WARE-UHY1 ┆ 31/12/17  ┆ … ┆ 5         ┆ 0.08      ┆ $1,001.18 ┆ $1,963.1 │
│ 000101    ┆           ┆ 004       ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ SO -      ┆ Online    ┆ WARE-NMK1 ┆ 31/12/17  ┆ … ┆ 3         ┆ 0.08      ┆ $3,348.66 ┆ $3,939.6 │
│ 000102    ┆           ┆ 003       ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ SO -      ┆ Distribut ┆ WARE-UHY1 ┆ 31/12/17  ┆ … ┆ 1         ┆ 0.05      ┆ $781.22   ┆ $1,775.5 │
│ 000103    ┆ or        ┆ 004       ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ SO -      ┆ Wholesale ┆ WARE-NMK1 ┆ 31/12/17  ┆ … ┆ 8         ┆ 0.08      ┆ $1,464.69 ┆ $2,324.9 │
│ 000104    ┆           ┆ 003       ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ SO -      ┆ Distribut ┆ WARE-NMK1 ┆ 10/4/2018 ┆ … ┆ 8         ┆ 0.1       ┆ $1,476.14 ┆ $1,822.4 │
│ 000105    ┆ or        ┆ 003       ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ SO -      ┆ In-Store  ┆ WARE-MKL1 ┆ 26/9/20   ┆ … ┆ 1         ┆ 0.08      ┆ $121.94   ┆ $234.50  │
│ 0008087   ┆           ┆ 006       ┆           ┆   ┆           ┆           ┆           ┆          │
│ SO -      ┆ Online    ┆ WARE-NMK1 ┆ 26/9/20   ┆ … ┆ 6         ┆ 0.05      ┆ $1,921.56 ┆ $3,202.6 │
│ 0008088   ┆           ┆ 003       ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ SO -      ┆ Online    ┆ WARE-UHY1 ┆ 26/9/20   ┆ … ┆ 5         ┆ 0.2       ┆ $2,792.76 ┆ $3,825.7 │
│ 0008089   ┆           ┆ 004       ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ SO -      ┆ Online    ┆ WARE-NMK1 ┆ 26/9/20   ┆ … ┆ 8         ┆ 0.1       ┆ $804.00   ┆ $1,072.0 │
│ 0008090   ┆           ┆ 003       ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ SO -      ┆ In-Store  ┆ WARE-UHY1 ┆ 26/9/20   ┆ … ┆ 5         ┆ 0.08      ┆ $1,370.82 ┆ $2,211.0 │
│ 0008091   ┆           ┆ 004       ┆           ┆   ┆           ┆           ┆           ┆ 0        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Display First Few Rows to Understand Structure of Data

In [6]:
print(df.head())

shape: (5, 16)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ order_num ┆ sales_cha ┆ warehouse ┆ procured_ ┆ … ┆ order_qua ┆ discount_ ┆ unit_cost ┆ unit_pri │
│ ber       ┆ nnel      ┆ _code     ┆ date      ┆   ┆ ntity     ┆ applied   ┆ ---       ┆ ce       │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ i64       ┆ f64       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ SO -      ┆ In-Store  ┆ WARE-UHY1 ┆ 31/12/17  ┆ … ┆ 5         ┆ 0.08      ┆ $1,001.18 ┆ $1,963.1 │
│ 000101    ┆           ┆ 004       ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ SO -      ┆ Online    ┆ WARE-NMK1 ┆ 31/12/17  ┆ … ┆ 3         ┆ 0.08      ┆ $3,348.66 ┆ $3,939.6 │
│ 000102    ┆           ┆ 003       ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ SO -      ┆ Distribut ┆ WARE-UHY1 ┆ 31/12/17  ┆ … ┆ 1         ┆ 0.05      ┆ $781.22   ┆ $1,775.5 │
│ 000103    ┆ or        ┆ 004       ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ SO -      ┆ Wholesale ┆ WARE-NMK1 ┆ 31/12/17  ┆ … ┆ 8         ┆ 0.08      ┆ $1,464.69 ┆ $2,324.9 │
│ 000104    ┆           ┆ 003       ┆           ┆   ┆           ┆           ┆           ┆ 0        │
│ SO -      ┆ Distribut ┆ WARE-NMK1 ┆ 10/4/2018 ┆ … ┆ 8         ┆ 0.1       ┆ $1,476.14 ┆ $1,822.4 │
│ 000105    ┆ or        ┆ 003       ┆           ┆   ┆           ┆           ┆           ┆ 0        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Retrieve Basic Information About DataFrame

In [7]:
print(df.shape)
print(df.dtypes)

(7991, 16)
[String, String, String, String, String, String, String, String, Int64, Int64, Int64, Int64, Int64, Float64, String, String]

### Display Summary Statistics for All Columns

In [8]:
summary = df.describe()
print(summary)

shape: (9, 17)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ order_num ┆ sales_cha ┆ warehouse ┆ … ┆ order_qua ┆ discount_ ┆ unit_cost ┆ unit_pri │
│ ---       ┆ ber       ┆ nnel      ┆ _code     ┆   ┆ ntity     ┆ applied   ┆ ---       ┆ ce       │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---      │
│           ┆ str       ┆ str       ┆ str       ┆   ┆ f64       ┆ f64       ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 7991      ┆ 7991      ┆ 7991      ┆ … ┆ 7991.0    ┆ 7991.0    ┆ 7991      ┆ 7991     │
│ null_coun ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0.0       ┆ 0.0       ┆ 0         ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ null      ┆ null      ┆ … ┆ 4.525341  ┆ 0.115649  ┆ null      ┆ null     │
│ std       ┆ null      ┆ null      ┆ null      ┆ … ┆ 2.312631  ┆ 0.085018  ┆ null      ┆ null     │
│ min       ┆ SO -      ┆ Distribut ┆ WARE-MKL1 ┆ … ┆ 1.0       ┆ 0.05      ┆ $1,001.18 ┆ $1,005.0 │
│           ┆ 0001000   ┆ or        ┆ 006       ┆   ┆           ┆           ┆           ┆ 0        │
│ 25%       ┆ null      ┆ null      ┆ null      ┆ … ┆ 3.0       ┆ 0.05      ┆ null      ┆ null     │
│ 50%       ┆ null      ┆ null      ┆ null      ┆ … ┆ 5.0       ┆ 0.08      ┆ null      ┆ null     │
│ 75%       ┆ null      ┆ null      ┆ null      ┆ … ┆ 7.0       ┆ 0.15      ┆ null      ┆ null     │
│ max       ┆ SO -      ┆ Wholesale ┆ WARE-XYS1 ┆ … ┆ 8.0       ┆ 0.4       ┆ $999.91   ┆ $998.30  │
│           ┆ 000999    ┆           ┆ 001       ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Find Longest Text Length in Each Column

In [9]:
# Create an empty list to store max lengths for each string column
longest_text_lengths = []

# Loop through the columns to check for string columns
string_columns = [col for col in df.columns if df[col].dtype == pl.Utf8]

max_lengths = {}
for col in string_columns:
    max_length = df.select(pl.col(col).str.len_chars().max()).to_numpy()[0, 0]
    max_lengths[col] = max_length

df_max_lengths = pl.DataFrame(max_lengths)

df_max_lengths

shape: (1, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ order_num ┆ sales_cha ┆ warehouse ┆ procured_ ┆ … ┆ delivery_ ┆ currency_ ┆ unit_cost ┆ unit_pri │
│ ber       ┆ nnel      ┆ _code     ┆ date      ┆   ┆ date      ┆ code      ┆ ---       ┆ ce       │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ u32       ┆ ---      │
│ u32       ┆ u32       ┆ u32       ┆ u32       ┆   ┆ u32       ┆ u32       ┆           ┆ u32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 12        ┆ 11        ┆ 12        ┆ 9         ┆ … ┆ 10        ┆ 3         ┆ 9         ┆ 9        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Retrieve Data Types of All Columns

In [10]:
print("Column data types:\n", df.dtypes)

Column data types:
 [String, String, String, String, String, String, String, String, Int64, Int64, Int64, Int64, Int64, Float64, String, String]

### Count Unique Values in Each Column

In [11]:
all_columns = [col for col in df.columns]

for col in all_columns:
    unique_counts = df[col].n_unique()
    print(f"Unique values in {col} :".rjust(48), f"{unique_counts}".ljust(6))

                 Unique values in order_number : 7991
                Unique values in sales_channel : 4
               Unique values in warehouse_code : 6
                Unique values in procured_date : 11
                   Unique values in order_date : 945
                    Unique values in ship_date : 966
                Unique values in delivery_date : 966
                Unique values in currency_code : 1
                Unique values in sales_team_id : 28
                  Unique values in customer_id : 50
                     Unique values in store_id : 367
                   Unique values in product_id : 47
               Unique values in order_quantity : 8
             Unique values in discount_applied : 7
                    Unique values in unit_cost : 5252
                   Unique values in unit_price : 664

### Check Distribution of Numerical Columns

In [12]:
numerical_cols = [item for item in all_columns if item not in string_columns]
numerical_cols = [item for item in numerical_cols if item not in ['id']]

numerical_cols

for col in numerical_cols:
    distribution = df.select(col).describe()
    print(col)
    print(distribution, '\n\n')

sales_team_id
shape: (9, 2)
┌────────────┬───────────────┐
│ statistic  ┆ sales_team_id │
│ ---        ┆ ---           │
│ str        ┆ f64           │
╞════════════╪═══════════════╡
│ count      ┆ 7991.0        │
│ null_count ┆ 0.0           │
│ mean       ┆ 14.384307     │
│ std        ┆ 7.986086      │
│ min        ┆ 1.0           │
│ 25%        ┆ 8.0           │
│ 50%        ┆ 14.0          │
│ 75%        ┆ 21.0          │
│ max        ┆ 28.0          │
└────────────┴───────────────┘


customer_id
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ customer_id │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 7991.0      │
│ null_count ┆ 0.0         │
│ mean       ┆ 25.457014   │
│ std        ┆ 14.414883   │
│ min        ┆ 1.0         │
│ 25%        ┆ 13.0        │
│ 50%        ┆ 25.0        │
│ 75%        ┆ 38.0        │
│ max        ┆ 50.0        │
└────────────┴─────────────┘


store_id
shape: (9, 2)
┌────────────┬────────────┐
│ statistic  ┆ store_id   │
│ ---        ┆ ---        │
│ str        ┆ f64        │
╞════════════╪════════════╡
│ count      ┆ 7991.0     │
│ null_count ┆ 0.0        │
│ mean       ┆ 183.850081 │
│ std        ┆ 105.903946 │
│ min        ┆ 1.0        │
│ 25%        ┆ 91.0       │
│ 50%        ┆ 183.0      │
│ 75%        ┆ 276.0      │
│ max        ┆ 367.0      │
└────────────┴────────────┘


product_id
shape: (9, 2)
┌────────────┬────────────┐
│ statistic  ┆ product_id │
│ ---        ┆ ---        │
│ str        ┆ f64        │
╞════════════╪════════════╡
│ count      ┆ 7991.0     │
│ null_count ┆ 0.0        │
│ mean       ┆ 23.771743  │
│ std        ┆ 13.526545  │
│ min        ┆ 1.0        │
│ 25%        ┆ 12.0       │
│ 50%        ┆ 24.0       │
│ 75%        ┆ 36.0       │
│ max        ┆ 47.0       │
└────────────┴────────────┘


order_quantity
shape: (9, 2)
┌────────────┬────────────────┐
│ statistic  ┆ order_quantity │
│ ---        ┆ ---            │
│ str        ┆ f64            │
╞════════════╪════════════════╡
│ count      ┆ 7991.0         │
│ null_count ┆ 0.0            │
│ mean       ┆ 4.525341       │
│ std        ┆ 2.312631       │
│ min        ┆ 1.0            │
│ 25%        ┆ 3.0            │
│ 50%        ┆ 5.0            │
│ 75%        ┆ 7.0            │
│ max        ┆ 8.0            │
└────────────┴────────────────┘


discount_applied
shape: (9, 2)
┌────────────┬──────────────────┐
│ statistic  ┆ discount_applied │
│ ---        ┆ ---              │
│ str        ┆ f64              │
╞════════════╪══════════════════╡
│ count      ┆ 7991.0           │
│ null_count ┆ 0.0              │
│ mean       ┆ 0.115649         │
│ std        ┆ 0.085018         │
│ min        ┆ 0.05             │
│ 25%        ┆ 0.05             │
│ 50%        ┆ 0.08             │
│ 75%        ┆ 0.15             │
│ max        ┆ 0.4              │
└────────────┴──────────────────┘

In [15]:
columns_to_check = [
    "sales_channel",
    "warehouse_code",
    "sales_team_id",
    "customer_id",
    "store_id",
    "product_id",
    "order_quantity",
    "discount_applied",
    "procured_date"
]

for col in columns_to_check:
    unique_values = df[col].unique().to_list()
    print(f"Unique values in {col}: {unique_values}")

Unique values in sales_channel: ['In-Store', 'Distributor', 'Wholesale', 'Online']
Unique values in warehouse_code: ['WARE-NMK1003', 'WARE-NBV1002', 'WARE-UHY1004', 'WARE-XYS1001', 'WARE-PUJ1005', 'WARE-MKL1006']
Unique values in sales_team_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]
Unique values in customer_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
Unique values in store_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367]
Unique values in product_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]
Unique values in order_quantity: [1, 2, 3, 4, 5, 6, 7, 8]
Unique values in discount_applied: [0.05, 0.08, 0.1, 0.15, 0.2, 0.3, 0.4]
Unique values in procured_date: ['19/7/18', '26/9/20', '4/2/2019', '27/10/18', '1/12/2019', '31/12/17', '15/5/19', '10/4/2018', '10/3/2020', '18/6/20', '23/8/19']

In [14]:
print("Missing values in each column")

for col in df.columns:
    missing_count = df[col].is_null().sum()
    print(f"{col}: {missing_count}")

Missing values in each column
order_number: 0
sales_channel: 0
warehouse_code: 0
procured_date: 0
order_date: 0
ship_date: 0
delivery_date: 0
currency_code: 0
sales_team_id: 0
customer_id: 0
store_id: 0
product_id: 0
order_quantity: 0
discount_applied: 0
unit_cost: 0
unit_price: 0