# German City Rainfall Data

## Installations

In [1]:
# !pip3 install --upgrade pip

In [2]:
# %pip install pycountry
# %pip install pycountry-convert
# %pip install geopy
# %pip install reverse_geocoder
# %pip install geopandas
# %pip install -U dataprep
# %pip install countryinfo
# %pip install pypopulation
# %pip install geotext
# %pip install tabulate

## Imports

In [3]:
import sys

from tabulate import tabulate
import numpy as np
import pandas as pd

import geopandas

## Display Imports & Their Versions

In [4]:
headers = ["Software/Library", "Version"]

table_data = [
    ['Python', sys.version[0:6]],
    ['NumPy', np.__version__],
    ['Pandas', pd.__version__],
    ['geopandas', geopandas.__version__]
    ]

print(tabulate(table_data, headers=headers, tablefmt="grid"))

+--------------------+-----------+
| Software/Library   | Version   |
+====================+===========+
| Python             | 3.11.4    |
+--------------------+-----------+
| NumPy              | 1.26.4    |
+--------------------+-----------+
| Pandas             | 2.2.3     |
+--------------------+-----------+
| geopandas          | 1.0.1     |
+--------------------+-----------+

## Import Dataset

In [6]:
gdf = geopandas.read_file("data/data.csv")

gdf

,City,Latitude,Longitude,Month,Year,Rainfall (mm),Elevation (m),Climate_Type,Temperature (°C),Humidity (%)
0,Berlin,52.52,13.405,1,2015,71.56,34,Oceanic,19.6,72
1,Berlin,52.52,13.405,2,2015,129.56,34,Oceanic,31.4,88
2,Berlin,52.52,13.405,3,2015,24.58,34,Oceanic,15.4,61
3,Berlin,52.52,13.405,4,2015,177.73,34,Oceanic,15.1,62
4,Berlin,52.52,13.405,5,2015,100.62,34,Oceanic,-3.0,57
...,...,...,...,...,...,...,...,...,...,...
1075,Hanover,52.3759,9.732,8,2023,34.14,55,Oceanic,32.2,61
1076,Hanover,52.3759,9.732,9,2023,6.09,55,Oceanic,12.2,57
1077,Hanover,52.3759,9.732,10,2023,40.89,55,Oceanic,-0.2,30
1078,Hanover,52.3759,9.732,11,2023,68.08,55,Oceanic,15.5,89
1079,Hanover,52.3759,9.732,12,2023,102.12,55,Oceanic,9.0,85

In [7]:
gdf.describe(include='all')

,City,Latitude,Longitude,Month,Year,Rainfall (mm),Elevation (m),Climate_Type,Temperature (°C),Humidity (%)
count,1080,1080,1080,1080,1080,1080,1080,1080,1080,1080
unique,10,10,10,12,9,1038,9,2,373,70
top,Berlin,52.52,13.405,1,2015,185.42,113,Oceanic,18.8,55
freq,108,108,108,90,120,2,216,648,9,24

### Display Unique Values

In [10]:
for column in gdf.columns:
    unique_values = gdf[column].unique()
    print(f"Column '{column}' has {len(unique_values)} unique values:")
    unique_values

Column 'City' has 10 unique values:
Column 'Latitude' has 10 unique values:
Column 'Longitude' has 10 unique values:
Column 'Month' has 12 unique values:
Column 'Year' has 9 unique values:
Column 'Rainfall (mm)' has 1038 unique values:
Column 'Elevation (m)' has 9 unique values:
Column 'Climate_Type' has 2 unique values:
Column 'Temperature (°C)' has 373 unique values:
Column 'Humidity (%)' has 70 unique values:

### Number of Unique Values in Each Feature

In [11]:
unique_counts = gdf.nunique()
print("Number of unique values per column:")
print(unique_counts)

Number of unique values per column:
City                  10
Latitude              10
Longitude             10
Month                 12
Year                   9
Rainfall (mm)       1038
Elevation (m)          9
Climate_Type           2
Temperature (°C)     373
Humidity (%)          70
dtype: int64

### Length of Longest Character Length In Each Feature

In [16]:
for column in gdf.select_dtypes(include='object').columns:
    max_length = gdf[column].astype(str).str.len().max()
    print(f"Longest string '{column}':\t\t{max_length}")

Longest string 'City':		10
Longest string 'Latitude':		7
Longest string 'Longitude':		7
Longest string 'Month':		2
Longest string 'Year':		4
Longest string 'Rainfall (mm)':		6
Longest string 'Elevation (m)':		3
Longest string 'Climate_Type':		11
Longest string 'Temperature (°C)':		4
Longest string 'Humidity (%)':		2

### Resources Used (links to libraries used in this project)

- GeoPandas: https://geopandas.org/en/stable/
- GeoPy: https://geopy.readthedocs.io/en/stable/#
- PyPopulation: https://pypi.org/project/pypopulation/
- GeoText: https://pypi.org/project/geotext/
- ReverseGeocoder: https://pypi.org/project/reverse_geocoder/