## Exploratory Data Analysis

### Import Libraries

In [1]:
import sys
import polars as pl
import polars.selectors as pol_sel

### Show Python & Library Versions

In [2]:
l = 8
r = 12

print("Python".rjust(l), ":", sys.version[0:6].ljust(r))
print("Polars".rjust(l), ":", pl.__version__.ljust(r))

  Python : 3.11.4
  Polars : 1.12.0

### Load CSV File into Polars DataFrame

In [3]:
df = pl.read_csv("data/DataCoSupplyChainDataset.csv")

df

shape: (180_519, 53)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ transacti ┆ actual_da ┆ scheduled ┆ benefit_p ┆ … ┆ product_p ┆ product_s ┆ shipping_ ┆ shipping │
│ on_type   ┆ ys_to_shi ┆ _days_to_ ┆ er_order  ┆   ┆ rice      ┆ tatus     ┆ date      ┆ _mode    │
│ ---       ┆ p         ┆ ship      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ ---       ┆ ---       ┆ f64       ┆   ┆ f64       ┆ i64       ┆ str       ┆ str      │
│           ┆ i64       ┆ i64       ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ DEBIT     ┆ 3         ┆ 4         ┆ 91.25     ┆ … ┆ 327.75    ┆ 0         ┆ 2/3/2018  ┆ Standard │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 22:56     ┆ Class    │
│ TRANSFER  ┆ 5         ┆ 4         ┆ -249.0899 ┆ … ┆ 327.75    ┆ 0         ┆ 1/18/2018 ┆ Standard │
│           ┆           ┆           ┆ 96        ┆   ┆           ┆           ┆ 12:27     ┆ Class    │
│ CASH      ┆ 4         ┆ 4         ┆ -247.7799 ┆ … ┆ 327.75    ┆ 0         ┆ 1/17/2018 ┆ Standard │
│           ┆           ┆           ┆ 99        ┆   ┆           ┆           ┆ 12:06     ┆ Class    │
│ DEBIT     ┆ 3         ┆ 4         ┆ 22.860001 ┆ … ┆ 327.75    ┆ 0         ┆ 1/16/2018 ┆ Standard │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 11:45     ┆ Class    │
│ PAYMENT   ┆ 2         ┆ 4         ┆ 134.21000 ┆ … ┆ 327.75    ┆ 0         ┆ 1/15/2018 ┆ Standard │
│           ┆           ┆           ┆ 7         ┆   ┆           ┆           ┆ 11:24     ┆ Class    │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ CASH      ┆ 4         ┆ 4         ┆ 40.0      ┆ … ┆ 399.98001 ┆ 0         ┆ 1/20/2016 ┆ Standard │
│           ┆           ┆           ┆           ┆   ┆ 1         ┆           ┆ 3:40      ┆ Class    │
│ DEBIT     ┆ 3         ┆ 2         ┆ -613.7700 ┆ … ┆ 399.98001 ┆ 0         ┆ 1/19/2016 ┆ Second   │
│           ┆           ┆           ┆ 19        ┆   ┆ 1         ┆           ┆ 1:34      ┆ Class    │
│ TRANSFER  ┆ 5         ┆ 4         ┆ 141.11000 ┆ … ┆ 399.98001 ┆ 0         ┆ 1/20/2016 ┆ Standard │
│           ┆           ┆           ┆ 1         ┆   ┆ 1         ┆           ┆ 21:00     ┆ Class    │
│ PAYMENT   ┆ 3         ┆ 4         ┆ 186.22999 ┆ … ┆ 399.98001 ┆ 0         ┆ 1/18/2016 ┆ Standard │
│           ┆           ┆           ┆ 6         ┆   ┆ 1         ┆           ┆ 20:18     ┆ Class    │
│ PAYMENT   ┆ 4         ┆ 4         ┆ 168.94999 ┆ … ┆ 399.98001 ┆ 0         ┆ 1/19/2016 ┆ Standard │
│           ┆           ┆           ┆ 7         ┆   ┆ 1         ┆           ┆ 18:54     ┆ Class    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Display First Few Rows to Understand Structure of Data

In [4]:
print(df.head())

shape: (5, 53)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ transacti ┆ actual_da ┆ scheduled ┆ benefit_p ┆ … ┆ product_p ┆ product_s ┆ shipping_ ┆ shipping │
│ on_type   ┆ ys_to_shi ┆ _days_to_ ┆ er_order  ┆   ┆ rice      ┆ tatus     ┆ date      ┆ _mode    │
│ ---       ┆ p         ┆ ship      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ ---       ┆ ---       ┆ f64       ┆   ┆ f64       ┆ i64       ┆ str       ┆ str      │
│           ┆ i64       ┆ i64       ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ DEBIT     ┆ 3         ┆ 4         ┆ 91.25     ┆ … ┆ 327.75    ┆ 0         ┆ 2/3/2018  ┆ Standard │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 22:56     ┆ Class    │
│ TRANSFER  ┆ 5         ┆ 4         ┆ -249.0899 ┆ … ┆ 327.75    ┆ 0         ┆ 1/18/2018 ┆ Standard │
│           ┆           ┆           ┆ 96        ┆   ┆           ┆           ┆ 12:27     ┆ Class    │
│ CASH      ┆ 4         ┆ 4         ┆ -247.7799 ┆ … ┆ 327.75    ┆ 0         ┆ 1/17/2018 ┆ Standard │
│           ┆           ┆           ┆ 99        ┆   ┆           ┆           ┆ 12:06     ┆ Class    │
│ DEBIT     ┆ 3         ┆ 4         ┆ 22.860001 ┆ … ┆ 327.75    ┆ 0         ┆ 1/16/2018 ┆ Standard │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 11:45     ┆ Class    │
│ PAYMENT   ┆ 2         ┆ 4         ┆ 134.21000 ┆ … ┆ 327.75    ┆ 0         ┆ 1/15/2018 ┆ Standard │
│           ┆           ┆           ┆ 7         ┆   ┆           ┆           ┆ 11:24     ┆ Class    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Retrieve Basic Information About DataFrame

In [5]:
print(df.shape)
print(df.dtypes)

(180519, 53)
[String, Int64, Int64, Float64, Float64, String, Int64, Int64, String, String, String, String, String, Int64, String, String, String, String, String, Int64, Int64, String, Float64, Float64, String, String, String, Int64, String, Int64, Int64, Float64, Float64, Int64, Float64, Float64, Int64, Float64, Float64, Float64, String, String, String, Int64, Int64, Int64, String, String, String, Float64, Int64, String, String]

### Display Summary Statistics for All Columns

In [6]:
summary = df.describe()
print(summary)

shape: (9, 54)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ transacti ┆ actual_da ┆ scheduled ┆ … ┆ product_p ┆ product_s ┆ shipping_ ┆ shipping │
│ ---       ┆ on_type   ┆ ys_to_shi ┆ _days_to_ ┆   ┆ rice      ┆ tatus     ┆ date      ┆ _mode    │
│ str       ┆ ---       ┆ p         ┆ ship      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ str       ┆ ---       ┆ ---       ┆   ┆ f64       ┆ f64       ┆ str       ┆ str      │
│           ┆           ┆ f64       ┆ f64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 180519    ┆ 180519.0  ┆ 180519.0  ┆ … ┆ 180519.0  ┆ 180519.0  ┆ 180519    ┆ 180519   │
│ null_coun ┆ 0         ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.0       ┆ 0         ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ 3.497654  ┆ 2.931847  ┆ … ┆ 141.23255 ┆ 0.0       ┆ null      ┆ null     │
│ std       ┆ null      ┆ 1.623722  ┆ 1.374449  ┆ … ┆ 139.73249 ┆ 0.0       ┆ null      ┆ null     │
│           ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆           ┆          │
│ min       ┆ CASH      ┆ 0.0       ┆ 0.0       ┆ … ┆ 9.99      ┆ 0.0       ┆ 1/1/2016  ┆ First    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ 0:22      ┆ Class    │
│ 25%       ┆ null      ┆ 2.0       ┆ 2.0       ┆ … ┆ 50.0      ┆ 0.0       ┆ null      ┆ null     │
│ 50%       ┆ null      ┆ 3.0       ┆ 4.0       ┆ … ┆ 59.990002 ┆ 0.0       ┆ null      ┆ null     │
│ 75%       ┆ null      ┆ 5.0       ┆ 4.0       ┆ … ┆ 199.99000 ┆ 0.0       ┆ null      ┆ null     │
│           ┆           ┆           ┆           ┆   ┆ 5         ┆           ┆           ┆          │
│ max       ┆ TRANSFER  ┆ 6.0       ┆ 4.0       ┆ … ┆ 1999.9899 ┆ 0.0       ┆ 9/9/2017  ┆ Standard │
│           ┆           ┆           ┆           ┆   ┆ 9         ┆           ┆ 9:08      ┆ Class    │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Find Longest Text Length in Each Column

In [7]:
# Create an empty list to store max lengths for each string column
longest_text_lengths = []

# Loop through the columns to check for string columns
string_columns = [col for col in df.columns if df[col].dtype == pl.Utf8]

max_lengths = {}
for col in string_columns:
    max_length = df.select(pl.col(col).str.len_chars().max()).to_numpy()[0, 0]
    max_lengths[col] = max_length

df_max_lengths = pl.DataFrame(max_lengths)

df_max_lengths

shape: (1, 25)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ transacti ┆ delivery_ ┆ category_ ┆ customer_ ┆ … ┆ product_i ┆ product_n ┆ shipping_ ┆ shipping │
│ on_type   ┆ status    ┆ name      ┆ city      ┆   ┆ mage      ┆ ame       ┆ date      ┆ _mode    │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ u32       ┆ u32       ┆ u32       ┆ u32       ┆   ┆ u32       ┆ u32       ┆ u32       ┆ u32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 8         ┆ 17        ┆ 20        ┆ 20        ┆ … ┆ 94        ┆ 45        ┆ 16        ┆ 14       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Retrieve Data Types of All Columns

In [8]:
print("Column data types:\n", df.dtypes)

Column data types:
 [String, Int64, Int64, Float64, Float64, String, Int64, Int64, String, String, String, String, String, Int64, String, String, String, String, String, Int64, Int64, String, Float64, Float64, String, String, String, Int64, String, Int64, Int64, Float64, Float64, Int64, Float64, Float64, Int64, Float64, Float64, Float64, String, String, String, Int64, Int64, Int64, String, String, String, Float64, Int64, String, String]

### Count Unique Values in Each Column

In [9]:
all_columns = [col for col in df.columns]

for col in all_columns:
    unique_counts = df[col].n_unique()
    print(f"Unique values in {col} :".rjust(48), f"{unique_counts}".ljust(6))

             Unique values in transaction_type : 4
          Unique values in actual_days_to_ship : 7
       Unique values in scheduled_days_to_ship : 4
            Unique values in benefit_per_order : 21998
           Unique values in sales_per_customer : 2927
              Unique values in delivery_status : 4
           Unique values in late_delivery_risk : 2
                  Unique values in category_id : 51
                Unique values in category_name : 50
                Unique values in customer_city : 563
             Unique values in customer_country : 2
               Unique values in customer_email : 1
               Unique values in customer_fname : 782
                  Unique values in customer_id : 20652
               Unique values in customer_lname : 1110
            Unique values in customer_password : 1
             Unique values in customer_segment : 3
               Unique values in customer_state : 46
              Unique values in customer_street : 7458
             Unique values in customer_zipcode : 996
                Unique values in department_id : 11
              Unique values in department_name : 11
                     Unique values in latitude : 11250
                    Unique values in longitude : 4487
                       Unique values in market : 5
                   Unique values in order_city : 3597
                Unique values in order_country : 164
            Unique values in order_customer_id : 20652
                   Unique values in order_date : 65752
                     Unique values in order_id : 65752
       Unique values in order_item_cardprod_id : 118
          Unique values in order_Item_discount : 1017
     Unique values in order_item_discount_rate : 18
                Unique values in order_item_id : 180519
     Unique values in order_item_product_price : 75
      Unique values in order_item_profit_ratio : 162
          Unique values in order_item_quantity : 5
                        Unique values in sales : 193
             Unique values in order_item_total : 2927
       Unique values in order_profit_per_order : 21998
                 Unique values in order_region : 23
                  Unique values in order_state : 1089
                 Unique values in order_status : 9
                Unique values in order_zipcode : 610
              Unique values in product_card_id : 118
          Unique values in product_category_id : 51
                 Unique values in product_desc : 1
                Unique values in product_image : 118
                 Unique values in product_name : 118
                Unique values in product_price : 75
               Unique values in product_status : 1
                Unique values in shipping_date : 63701
                Unique values in shipping_mode : 4

### Check Distribution of Numerical Columns

In [10]:
numerical_cols = [item for item in all_columns if item not in string_columns]
numerical_cols = [item for item in numerical_cols if item not in ['id']]

numerical_cols

for col in numerical_cols:
    distribution = df.select(col).describe()
    print(col)
    print(distribution, '\n\n')

actual_days_to_ship
shape: (9, 2)
┌────────────┬─────────────────────┐
│ statistic  ┆ actual_days_to_ship │
│ ---        ┆ ---                 │
│ str        ┆ f64                 │
╞════════════╪═════════════════════╡
│ count      ┆ 180519.0            │
│ null_count ┆ 0.0                 │
│ mean       ┆ 3.497654            │
│ std        ┆ 1.623722            │
│ min        ┆ 0.0                 │
│ 25%        ┆ 2.0                 │
│ 50%        ┆ 3.0                 │
│ 75%        ┆ 5.0                 │
│ max        ┆ 6.0                 │
└────────────┴─────────────────────┘


scheduled_days_to_ship
shape: (9, 2)
┌────────────┬────────────────────────┐
│ statistic  ┆ scheduled_days_to_ship │
│ ---        ┆ ---                    │
│ str        ┆ f64                    │
╞════════════╪════════════════════════╡
│ count      ┆ 180519.0               │
│ null_count ┆ 0.0                    │
│ mean       ┆ 2.931847               │
│ std        ┆ 1.374449               │
│ min        ┆ 0.0                    │
│ 25%        ┆ 2.0                    │
│ 50%        ┆ 4.0                    │
│ 75%        ┆ 4.0                    │
│ max        ┆ 4.0                    │
└────────────┴────────────────────────┘


benefit_per_order
shape: (9, 2)
┌────────────┬───────────────────┐
│ statistic  ┆ benefit_per_order │
│ ---        ┆ ---               │
│ str        ┆ f64               │
╞════════════╪═══════════════════╡
│ count      ┆ 180519.0          │
│ null_count ┆ 0.0               │
│ mean       ┆ 21.974989         │
│ std        ┆ 104.433526        │
│ min        ┆ -4274.97998       │
│ 25%        ┆ 7.0               │
│ 50%        ┆ 31.52             │
│ 75%        ┆ 64.800003         │
│ max        ┆ 911.799988        │
└────────────┴───────────────────┘


sales_per_customer
shape: (9, 2)
┌────────────┬────────────────────┐
│ statistic  ┆ sales_per_customer │
│ ---        ┆ ---                │
│ str        ┆ f64                │
╞════════════╪════════════════════╡
│ count      ┆ 180519.0           │
│ null_count ┆ 0.0                │
│ mean       ┆ 183.107609         │
│ std        ┆ 120.04367          │
│ min        ┆ 7.49               │
│ 25%        ┆ 104.379997         │
│ 50%        ┆ 163.990005         │
│ 75%        ┆ 247.399994         │
│ max        ┆ 1939.98999         │
└────────────┴────────────────────┘


late_delivery_risk
shape: (9, 2)
┌────────────┬────────────────────┐
│ statistic  ┆ late_delivery_risk │
│ ---        ┆ ---                │
│ str        ┆ f64                │
╞════════════╪════════════════════╡
│ count      ┆ 180519.0           │
│ null_count ┆ 0.0                │
│ mean       ┆ 0.548291           │
│ std        ┆ 0.497664           │
│ min        ┆ 0.0                │
│ 25%        ┆ 0.0                │
│ 50%        ┆ 1.0                │
│ 75%        ┆ 1.0                │
│ max        ┆ 1.0                │
└────────────┴────────────────────┘


category_id
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ category_id │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 180519.0    │
│ null_count ┆ 0.0         │
│ mean       ┆ 31.851451   │
│ std        ┆ 15.640064   │
│ min        ┆ 2.0         │
│ 25%        ┆ 18.0        │
│ 50%        ┆ 29.0        │
│ 75%        ┆ 45.0        │
│ max        ┆ 76.0        │
└────────────┴─────────────┘


customer_id
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ customer_id │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 180519.0    │
│ null_count ┆ 0.0         │
│ mean       ┆ 6691.379495 │
│ std        ┆ 4162.918106 │
│ min        ┆ 1.0         │
│ 25%        ┆ 3259.0      │
│ 50%        ┆ 6457.0      │
│ 75%        ┆ 9779.0      │
│ max        ┆ 20757.0     │
└────────────┴─────────────┘


customer_zipcode
shape: (9, 2)
┌────────────┬──────────────────┐
│ statistic  ┆ customer_zipcode │
│ ---        ┆ ---              │
│ str        ┆ f64              │
╞════════════╪══════════════════╡
│ count      ┆ 180516.0         │
│ null_count ┆ 3.0              │
│ mean       ┆ 35921.126914     │
│ std        ┆ 37542.461122     │
│ min        ┆ 603.0            │
│ 25%        ┆ 725.0            │
│ 50%        ┆ 19380.0          │
│ 75%        ┆ 78207.0          │
│ max        ┆ 99205.0          │
└────────────┴──────────────────┘


department_id
shape: (9, 2)
┌────────────┬───────────────┐
│ statistic  ┆ department_id │
│ ---        ┆ ---           │
│ str        ┆ f64           │
╞════════════╪═══════════════╡
│ count      ┆ 180519.0      │
│ null_count ┆ 0.0           │
│ mean       ┆ 5.44346       │
│ std        ┆ 1.629246      │
│ min        ┆ 2.0           │
│ 25%        ┆ 4.0           │
│ 50%        ┆ 5.0           │
│ 75%        ┆ 7.0           │
│ max        ┆ 12.0          │
└────────────┴───────────────┘


latitude
shape: (9, 2)
┌────────────┬────────────┐
│ statistic  ┆ latitude   │
│ ---        ┆ ---        │
│ str        ┆ f64        │
╞════════════╪════════════╡
│ count      ┆ 180519.0   │
│ null_count ┆ 0.0        │
│ mean       ┆ 29.719955  │
│ std        ┆ 9.813646   │
│ min        ┆ -33.937553 │
│ 25%        ┆ 18.265432  │
│ 50%        ┆ 33.144863  │
│ 75%        ┆ 39.279617  │
│ max        ┆ 48.781933  │
└────────────┴────────────┘


longitude
shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ longitude   │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 180519.0    │
│ null_count ┆ 0.0         │
│ mean       ┆ -84.915675  │
│ std        ┆ 21.433241   │
│ min        ┆ -158.025986 │
│ 25%        ┆ -98.446312  │
│ 50%        ┆ -76.847908  │
│ 75%        ┆ -66.370583  │
│ max        ┆ 115.263077  │
└────────────┴─────────────┘


order_customer_id
shape: (9, 2)
┌────────────┬───────────────────┐
│ statistic  ┆ order_customer_id │
│ ---        ┆ ---               │
│ str        ┆ f64               │
╞════════════╪═══════════════════╡
│ count      ┆ 180519.0          │
│ null_count ┆ 0.0               │
│ mean       ┆ 6691.379495       │
│ std        ┆ 4162.918106       │
│ min        ┆ 1.0               │
│ 25%        ┆ 3259.0            │
│ 50%        ┆ 6457.0            │
│ 75%        ┆ 9779.0            │
│ max        ┆ 20757.0           │
└────────────┴───────────────────┘


order_id
shape: (9, 2)
┌────────────┬──────────────┐
│ statistic  ┆ order_id     │
│ ---        ┆ ---          │
│ str        ┆ f64          │
╞════════════╪══════════════╡
│ count      ┆ 180519.0     │
│ null_count ┆ 0.0          │
│ mean       ┆ 36221.894903 │
│ std        ┆ 21045.379569 │
│ min        ┆ 1.0          │
│ 25%        ┆ 18058.0      │
│ 50%        ┆ 36140.0      │
│ 75%        ┆ 54144.0      │
│ max        ┆ 77204.0      │
└────────────┴──────────────┘


order_item_cardprod_id
shape: (9, 2)
┌────────────┬────────────────────────┐
│ statistic  ┆ order_item_cardprod_id │
│ ---        ┆ ---                    │
│ str        ┆ f64                    │
╞════════════╪════════════════════════╡
│ count      ┆ 180519.0               │
│ null_count ┆ 0.0                    │
│ mean       ┆ 692.509764             │
│ std        ┆ 336.446807             │
│ min        ┆ 19.0                   │
│ 25%        ┆ 403.0                  │
│ 50%        ┆ 627.0                  │
│ 75%        ┆ 1004.0                 │
│ max        ┆ 1363.0                 │
└────────────┴────────────────────────┘


order_Item_discount
shape: (9, 2)
┌────────────┬─────────────────────┐
│ statistic  ┆ order_Item_discount │
│ ---        ┆ ---                 │
│ str        ┆ f64                 │
╞════════════╪═════════════════════╡
│ count      ┆ 180519.0            │
│ null_count ┆ 0.0                 │
│ mean       ┆ 20.664741           │
│ std        ┆ 21.800901           │
│ min        ┆ 0.0                 │
│ 25%        ┆ 5.4                 │
│ 50%        ┆ 14.0                │
│ 75%        ┆ 29.99               │
│ max        ┆ 500.0               │
└────────────┴─────────────────────┘


order_item_discount_rate
shape: (9, 2)
┌────────────┬──────────────────────────┐
│ statistic  ┆ order_item_discount_rate │
│ ---        ┆ ---                      │
│ str        ┆ f64                      │
╞════════════╪══════════════════════════╡
│ count      ┆ 180519.0                 │
│ null_count ┆ 0.0                      │
│ mean       ┆ 0.101668                 │
│ std        ┆ 0.070415                 │
│ min        ┆ 0.0                      │
│ 25%        ┆ 0.04                     │
│ 50%        ┆ 0.1                      │
│ 75%        ┆ 0.16                     │
│ max        ┆ 0.25                     │
└────────────┴──────────────────────────┘


order_item_id
shape: (9, 2)
┌────────────┬───────────────┐
│ statistic  ┆ order_item_id │
│ ---        ┆ ---           │
│ str        ┆ f64           │
╞════════════╪═══════════════╡
│ count      ┆ 180519.0      │
│ null_count ┆ 0.0           │
│ mean       ┆ 90260.0       │
│ std        ┆ 52111.490959  │
│ min        ┆ 1.0           │
│ 25%        ┆ 45131.0       │
│ 50%        ┆ 90260.0       │
│ 75%        ┆ 135390.0      │
│ max        ┆ 180519.0      │
└────────────┴───────────────┘


order_item_product_price
shape: (9, 2)
┌────────────┬──────────────────────────┐
│ statistic  ┆ order_item_product_price │
│ ---        ┆ ---                      │
│ str        ┆ f64                      │
╞════════════╪══════════════════════════╡
│ count      ┆ 180519.0                 │
│ null_count ┆ 0.0                      │
│ mean       ┆ 141.23255                │
│ std        ┆ 139.732492               │
│ min        ┆ 9.99                     │
│ 25%        ┆ 50.0                     │
│ 50%        ┆ 59.990002                │
│ 75%        ┆ 199.990005               │
│ max        ┆ 1999.98999               │
└────────────┴──────────────────────────┘


order_item_profit_ratio
shape: (9, 2)
┌────────────┬─────────────────────────┐
│ statistic  ┆ order_item_profit_ratio │
│ ---        ┆ ---                     │
│ str        ┆ f64                     │
╞════════════╪═════════════════════════╡
│ count      ┆ 180519.0                │
│ null_count ┆ 0.0                     │
│ mean       ┆ 0.120647                │
│ std        ┆ 0.466796                │
│ min        ┆ -2.75                   │
│ 25%        ┆ 0.08                    │
│ 50%        ┆ 0.27                    │
│ 75%        ┆ 0.36                    │
│ max        ┆ 0.5                     │
└────────────┴─────────────────────────┘


order_item_quantity
shape: (9, 2)
┌────────────┬─────────────────────┐
│ statistic  ┆ order_item_quantity │
│ ---        ┆ ---                 │
│ str        ┆ f64                 │
╞════════════╪═════════════════════╡
│ count      ┆ 180519.0            │
│ null_count ┆ 0.0                 │
│ mean       ┆ 2.127638            │
│ std        ┆ 1.453451            │
│ min        ┆ 1.0                 │
│ 25%        ┆ 1.0                 │
│ 50%        ┆ 1.0                 │
│ 75%        ┆ 3.0                 │
│ max        ┆ 5.0                 │
└────────────┴─────────────────────┘


sales
shape: (9, 2)
┌────────────┬────────────┐
│ statistic  ┆ sales      │
│ ---        ┆ ---        │
│ str        ┆ f64        │
╞════════════╪════════════╡
│ count      ┆ 180519.0   │
│ null_count ┆ 0.0        │
│ mean       ┆ 203.772096 │
│ std        ┆ 132.273077 │
│ min        ┆ 9.99       │
│ 25%        ┆ 119.980003 │
│ 50%        ┆ 199.919998 │
│ 75%        ┆ 299.950012 │
│ max        ┆ 1999.98999 │
└────────────┴────────────┘


order_item_total
shape: (9, 2)
┌────────────┬──────────────────┐
│ statistic  ┆ order_item_total │
│ ---        ┆ ---              │
│ str        ┆ f64              │
╞════════════╪══════════════════╡
│ count      ┆ 180519.0         │
│ null_count ┆ 0.0              │
│ mean       ┆ 183.107609       │
│ std        ┆ 120.04367        │
│ min        ┆ 7.49             │
│ 25%        ┆ 104.379997       │
│ 50%        ┆ 163.990005       │
│ 75%        ┆ 247.399994       │
│ max        ┆ 1939.98999       │
└────────────┴──────────────────┘


order_profit_per_order
shape: (9, 2)
┌────────────┬────────────────────────┐
│ statistic  ┆ order_profit_per_order │
│ ---        ┆ ---                    │
│ str        ┆ f64                    │
╞════════════╪════════════════════════╡
│ count      ┆ 180519.0               │
│ null_count ┆ 0.0                    │
│ mean       ┆ 21.974989              │
│ std        ┆ 104.433526             │
│ min        ┆ -4274.97998            │
│ 25%        ┆ 7.0                    │
│ 50%        ┆ 31.52                  │
│ 75%        ┆ 64.800003              │
│ max        ┆ 911.799988             │
└────────────┴────────────────────────┘


order_zipcode
shape: (9, 2)
┌────────────┬───────────────┐
│ statistic  ┆ order_zipcode │
│ ---        ┆ ---           │
│ str        ┆ f64           │
╞════════════╪═══════════════╡
│ count      ┆ 24840.0       │
│ null_count ┆ 155679.0      │
│ mean       ┆ 55426.132327  │
│ std        ┆ 31919.279101  │
│ min        ┆ 1040.0        │
│ 25%        ┆ 23464.0       │
│ 50%        ┆ 59405.0       │
│ 75%        ┆ 90008.0       │
│ max        ┆ 99301.0       │
└────────────┴───────────────┘


product_card_id
shape: (9, 2)
┌────────────┬─────────────────┐
│ statistic  ┆ product_card_id │
│ ---        ┆ ---             │
│ str        ┆ f64             │
╞════════════╪═════════════════╡
│ count      ┆ 180519.0        │
│ null_count ┆ 0.0             │
│ mean       ┆ 692.509764      │
│ std        ┆ 336.446807      │
│ min        ┆ 19.0            │
│ 25%        ┆ 403.0           │
│ 50%        ┆ 627.0           │
│ 75%        ┆ 1004.0          │
│ max        ┆ 1363.0          │
└────────────┴─────────────────┘


product_category_id
shape: (9, 2)
┌────────────┬─────────────────────┐
│ statistic  ┆ product_category_id │
│ ---        ┆ ---                 │
│ str        ┆ f64                 │
╞════════════╪═════════════════════╡
│ count      ┆ 180519.0            │
│ null_count ┆ 0.0                 │
│ mean       ┆ 31.851451           │
│ std        ┆ 15.640064           │
│ min        ┆ 2.0                 │
│ 25%        ┆ 18.0                │
│ 50%        ┆ 29.0                │
│ 75%        ┆ 45.0                │
│ max        ┆ 76.0                │
└────────────┴─────────────────────┘


product_price
shape: (9, 2)
┌────────────┬───────────────┐
│ statistic  ┆ product_price │
│ ---        ┆ ---           │
│ str        ┆ f64           │
╞════════════╪═══════════════╡
│ count      ┆ 180519.0      │
│ null_count ┆ 0.0           │
│ mean       ┆ 141.23255     │
│ std        ┆ 139.732492    │
│ min        ┆ 9.99          │
│ 25%        ┆ 50.0          │
│ 50%        ┆ 59.990002     │
│ 75%        ┆ 199.990005    │
│ max        ┆ 1999.98999    │
└────────────┴───────────────┘


product_status
shape: (9, 2)
┌────────────┬────────────────┐
│ statistic  ┆ product_status │
│ ---        ┆ ---            │
│ str        ┆ f64            │
╞════════════╪════════════════╡
│ count      ┆ 180519.0       │
│ null_count ┆ 0.0            │
│ mean       ┆ 0.0            │
│ std        ┆ 0.0            │
│ min        ┆ 0.0            │
│ 25%        ┆ 0.0            │
│ 50%        ┆ 0.0            │
│ 75%        ┆ 0.0            │
│ max        ┆ 0.0            │
└────────────┴────────────────┘

### List Unique Values for Select Columns/Features

In [11]:
cols_2_check = [
    "transaction_type",
    "actual_days_to_ship",
    "scheduled_days_to_ship",
    "late_delivery_risk",
    "delivery_status",
    "category_id",
    "category_name",
    "customer_country",
    "customer_email",
    "customer_password",
    "customer_state",
    "customer_segment",
    "department_id",
    "department_name",
    "market",
    "order_country",
    "order_item_cardprod_id",
    "order_item_discount_rate",
    "order_item_product_price",
    "order_item_profit_ratio",
    "order_item_quantity",
    "sales",
    "order_region",
    "order_status",
    "product_card_id",
    "product_category_id",
    "product_desc",
    "product_image",
    "product_name",
    "product_price",
    "product_status",
    "shipping_mode"
]

for col in cols_2_check:
    unique_values = df[col].unique().sort().to_list()
    print(f"Column: {col} [{len(unique_values)}]")
    print(f"Unique values: {unique_values}\n")

Column: transaction_type [4]
Unique values: ['CASH', 'DEBIT', 'PAYMENT', 'TRANSFER']

Column: actual_days_to_ship [7]
Unique values: [0, 1, 2, 3, 4, 5, 6]

Column: scheduled_days_to_ship [4]
Unique values: [0, 1, 2, 4]

Column: late_delivery_risk [2]
Unique values: [0, 1]

Column: delivery_status [4]
Unique values: ['Advance shipping', 'Late delivery', 'Shipping canceled', 'Shipping on time']

Column: category_id [51]
Unique values: [2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 16, 17, 18, 24, 26, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 40, 41, 43, 44, 45, 46, 48, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76]

Column: category_name [50]
Unique values: ['Accessories', 'As Seen on  TV!', 'Baby ', 'Baseball & Softball', 'Basketball', 'Books ', 'Boxing & MMA', 'CDs ', 'Cameras ', 'Camping & Hiking', 'Cardio Equipment', "Children's Clothing", 'Cleats', 'Computers', 'Consumer Electronics', 'Crafts', 'DVDs', 'Electronics', 'Fishing', 'Fitness Accessories', 'Garden', "Girls' Apparel", 'Golf Apparel', 'Golf Bags & Carts', 'Golf Balls', 'Golf Gloves', 'Golf Shoes', 'Health and Beauty', 'Hockey', 'Hunting & Shooting', 'Indoor/Outdoor Games', "Kids' Golf Clubs", 'Lacrosse', "Men's Clothing", "Men's Footwear", "Men's Golf Clubs", 'Music', 'Pet Supplies', 'Shop By Sport', 'Soccer', 'Sporting Goods', 'Strength Training', 'Tennis & Racquet', 'Toys', 'Trade-In', 'Video Games', 'Water Sports', "Women's Apparel", "Women's Clothing", "Women's Golf Clubs"]

Column: customer_country [2]
Unique values: ['EE. UU.', 'Puerto Rico']

Column: customer_email [1]
Unique values: ['XXXXXXXXX']

Column: customer_password [1]
Unique values: ['XXXXXXXXX']

Column: customer_state [46]
Unique values: ['91732', '95758', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'MI', 'MN', 'MO', 'MT', 'NC', 'ND', 'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'PR', 'RI', 'SC', 'TN', 'TX', 'UT', 'VA', 'WA', 'WI', 'WV']

Column: customer_segment [3]
Unique values: ['Consumer', 'Corporate', 'Home Office']

Column: department_id [11]
Unique values: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

Column: department_name [11]
Unique values: ['Apparel', 'Book Shop', 'Discs Shop', 'Fan Shop', 'Fitness', 'Footwear', 'Golf', 'Health and Beauty ', 'Outdoors', 'Pet Shop', 'Technology']

Column: market [5]
Unique values: ['Africa', 'Europe', 'LATAM', 'Pacific Asia', 'USCA']

Column: order_country [164]
Unique values: ['Afganist�n', 'Albania', 'Alemania', 'Angola', 'Arabia Saud�', 'Argelia', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaiy�n', 'Banglad�s', 'Barbados', 'Bar�in', 'Belice', 'Ben�n', 'Bielorrusia', 'Bolivia', 'Bosnia y Herzegovina', 'Botsuana', 'Brasil', 'Bulgaria', 'Burkina Faso', 'Burundi', 'But�n', 'B�lgica', 'Camboya', 'Camer�n', 'Canada', 'Chad', 'Chile', 'China', 'Chipre', 'Colombia', 'Corea del Sur', 'Costa Rica', 'Costa de Marfil', 'Croacia', 'Cuba', 'Dinamarca', 'Ecuador', 'Egipto', 'El Salvador', 'Emiratos �rabes Unidos', 'Eritrea', 'Eslovaquia', 'Eslovenia', 'Espa�a', 'Estados Unidos', 'Estonia', 'Etiop�a', 'Filipinas', 'Finlandia', 'Francia', 'Gab�n', 'Georgia', 'Ghana', 'Grecia', 'Guadalupe', 'Guatemala', 'Guayana Francesa', 'Guinea', 'Guinea Ecuatorial', 'Guinea-Bissau', 'Guyana', 'Hait�', 'Honduras', 'Hong Kong', 'Hungr�a', 'India', 'Indonesia', 'Irak', 'Irlanda', 'Ir�n', 'Israel', 'Italia', 'Jamaica', 'Jap�n', 'Jordania', 'Kazajist�n', 'Kenia', 'Kirguist�n', 'Kuwait', 'Laos', 'Lesoto', 'Liberia', 'Libia', 'Lituania', 'Luxemburgo', 'L�bano', 'Macedonia', 'Madagascar', 'Malasia', 'Mali', 'Marruecos', 'Martinica', 'Mauritania', 'Moldavia', 'Mongolia', 'Montenegro', 'Mozambique', 'Myanmar (Birmania)', 'M�xico', 'Namibia', 'Nepal', 'Nicaragua', 'Nigeria', 'Noruega', 'Nueva Zelanda', 'N�ger', 'Om�n', 'Pakist�n', 'Panam�', 'Pap�a Nueva Guinea', 'Paraguay', 'Pa�ses Bajos', 'Per�', 'Polonia', 'Portugal', 'Qatar', 'Reino Unido', 'Rep�blica Centroafricana', 'Rep�blica Checa', 'Rep�blica Democr�tica del Congo', 'Rep�blica Dominicana', 'Rep�blica de Gambia', 'Rep�blica del Congo', 'Ruanda', 'Rumania', 'Rusia', 'Senegal', 'Serbia', 'Sierra Leona', 'Singapur', 'Siria', 'Somalia', 'Sri Lanka', 'Suazilandia', 'SudAfrica', 'Sud�n', 'Sud�n del Sur', 'Suecia', 'Suiza', 'Surinam', 'S�hara Occidental', 'Tailandia', 'Taiw�n', 'Tanzania', 'Tayikist�n', 'Togo', 'Trinidad y Tobago', 'Turkmenist�n', 'Turqu�a', 'T�nez', 'Ucrania', 'Uganda', 'Uruguay', 'Uzbekist�n', 'Venezuela', 'Vietnam', 'Yemen', 'Yibuti', 'Zambia', 'Zimbabue']

Column: order_item_cardprod_id [118]
Unique values: [19, 24, 35, 37, 44, 58, 60, 61, 78, 93, 116, 127, 134, 135, 172, 191, 203, 208, 216, 226, 235, 249, 251, 258, 273, 276, 278, 282, 295, 303, 305, 306, 311, 359, 364, 365, 403, 502, 564, 565, 567, 572, 607, 625, 627, 642, 646, 647, 652, 666, 671, 677, 691, 703, 705, 715, 724, 725, 728, 730, 743, 768, 771, 773, 775, 777, 778, 786, 792, 793, 797, 804, 810, 818, 821, 822, 823, 825, 828, 835, 845, 858, 860, 885, 886, 893, 897, 905, 906, 917, 924, 926, 957, 977, 981, 982, 1004, 1014, 1059, 1073, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363]

Column: order_item_discount_rate [18]
Unique values: [0.0, 0.01, 0.02, 0.029999999, 0.039999999, 0.050000001, 0.059999999, 0.07, 0.090000004, 0.100000001, 0.119999997, 0.129999995, 0.150000006, 0.159999996, 0.170000002, 0.180000007, 0.200000003, 0.25]

Column: order_item_product_price [75]
Unique values: [9.989999771, 11.28999996, 11.53999996, 14.98999977, 15.98999977, 17.98999977, 19.98999977, 21.98999977, 22.0, 24.98999977, 25.0, 27.98999977, 29.98999977, 30.0, 31.07999992, 31.98999977, 34.99000168, 39.75, 39.99000168, 44.99000168, 47.99000168, 49.97999954, 50.0, 51.99000168, 54.97000122, 59.08000183, 59.99000168, 65.0, 70.0, 79.98999786, 80.0, 84.40000153, 89.98999786, 94.98999786, 99.0, 99.94999695, 99.98999786, 100.0, 108.0, 109.9499969, 109.9899979, 119.9899979, 124.9899979, 129.9900055, 134.9900055, 149.9900055, 159.9900055, 164.3800049, 169.9900055, 179.9900055, 189.0, 199.0, 199.9900055, 209.9900055, 210.8500061, 215.8200073, 249.9900055, 252.8800049, 260.6499939, 293.0400085, 299.980011, 299.9899902, 327.75, 329.9899902, 349.9899902, 357.1000061, 399.980011, 399.9899902, 452.0400085, 461.480011, 532.5800171, 599.9899902, 999.9899902, 1500.0, 1999.98999]

Column: order_item_profit_ratio [162]
Unique values: [-2.75, -2.700000048, -2.650000095, -2.599999905, -2.549999952, -2.5, -2.450000048, -2.349999905, -2.299999952, -2.25, -2.200000048, -2.099999905, -2.069999933, -2.049999952, -1.799999952, -1.769999981, -1.75, -1.700000048, -1.649999976, -1.600000024, -1.570000052, -1.549999952, -1.5, -1.470000029, -1.429999948, -1.399999976, -1.370000005, -1.330000043, -1.299999952, -1.279999971, -1.25, -1.230000019, -1.200000048, -1.179999948, -1.100000024, -1.080000043, -1.049999952, -0.980000019, -0.930000007, -0.899999976, -0.879999995, -0.860000014, -0.850000024, -0.829999983, -0.800000012, -0.779999971, -0.769999981, -0.75, -0.74000001, -0.730000019, -0.699999988, -0.680000007, -0.670000017, -0.660000026, -0.649999976, -0.639999986, -0.629999995, -0.620000005, -0.600000024, -0.579999983, -0.569999993, -0.560000002, -0.550000012, -0.540000021, -0.529999971, -0.519999981, -0.5, -0.49000001, -0.479999989, -0.460000008, -0.449999988, -0.439999998, -0.430000007, -0.419999987, -0.400000006, -0.379999995, -0.370000005, -0.360000014, -0.349999994, -0.340000004, -0.330000013, -0.319999993, -0.310000002, -0.300000012, -0.280000001, -0.270000011, -0.25999999, -0.25, -0.239999995, -0.230000004, -0.219999999, -0.209999993, -0.200000003, -0.189999998, -0.180000007, -0.170000002, -0.159999996, -0.150000006, -0.140000001, -0.129999995, -0.109999999, -0.100000001, -0.090000004, -0.079999998, -0.07, -0.059999999, -0.050000001, -0.039999999, -0.029999999, -0.02, -0.01, 0.0, 0.01, 0.02, 0.029999999, 0.039999999, 0.050000001, 0.059999999, 0.07, 0.079999998, 0.090000004, 0.100000001, 0.109999999, 0.119999997, 0.129999995, 0.140000001, 0.150000006, 0.159999996, 0.170000002, 0.180000007, 0.189999998, 0.200000003, 0.209999993, 0.219999999, 0.230000004, 0.239999995, 0.25, 0.25999999, 0.270000011, 0.280000001, 0.289999992, 0.300000012, 0.310000002, 0.319999993, 0.330000013, 0.340000004, 0.349999994, 0.360000014, 0.370000005, 0.379999995, 0.389999986, 0.400000006, 0.409999996, 0.419999987, 0.430000007, 0.439999998, 0.449999988, 0.460000008, 0.469999999, 0.479999989, 0.49000001, 0.5]

Column: order_item_quantity [5]
Unique values: [1, 2, 3, 4, 5]

Column: sales [193]
Unique values: [9.989999771, 11.28999996, 11.53999996, 14.98999977, 15.98999977, 17.98999977, 19.97999954, 19.98999977, 21.98999977, 22.0, 24.98999977, 25.0, 27.98999977, 29.96999931, 29.97999954, 29.98999977, 30.0, 31.07999992, 31.97999954, 31.98999977, 34.99000168, 35.97999954, 39.75, 39.95999908, 39.97999954, 39.99000168, 43.97999954, 44.0, 44.97000122, 44.99000168, 47.97000122, 47.99000168, 49.95000076, 49.97999954, 50.0, 51.99000168, 53.97000122, 54.97000122, 55.97999954, 59.08000183, 59.95999908, 59.97000122, 59.97999954, 59.99000168, 60.0, 63.95999908, 63.97999954, 65.0, 65.97000122, 66.0, 69.98000336, 70.0, 71.95999908, 74.94999695, 74.97000122, 75.0, 79.94999695, 79.95999908, 79.98000336, 79.98999786, 80.0, 83.97000122, 84.40000153, 87.95999908, 88.0, 89.94999695, 89.97000122, 89.98000336, 89.98999786, 90.0, 94.98999786, 95.97000122, 95.98000336, 99.0, 99.94999695, 99.95999908, 99.98999786, 100.0, 103.9800034, 104.9700012, 108.0, 109.9400024, 109.9499969, 109.9899979, 110.0, 111.9599991, 119.9599991, 119.9700012, 119.9800034, 119.9899979, 120.0, 124.9499969, 124.9899979, 125.0, 127.9599991, 129.9900055, 130.0, 134.9700012, 134.9900055, 139.9499969, 139.9600067, 140.0, 143.9700012, 149.9400024, 149.9499969, 149.9900055, 150.0, 155.9700012, 159.9499969, 159.9600067, 159.9799957, 159.9900055, 160.0, 164.3800049, 164.9100037, 169.9900055, 174.9499969, 179.9600067, 179.9700012, 179.9799957, 179.9900055, 189.0, 189.9799957, 191.9600067, 195.0, 198.0, 199.0, 199.8999939, 199.9199982, 199.9499969, 199.9799957, 199.9900055, 200.0, 207.9600067, 209.9900055, 210.0, 210.8500061, 215.8200073, 219.8800049, 224.9499969, 239.9499969, 239.9600067, 239.9700012, 240.0, 249.8999939, 249.9900055, 250.0, 252.8800049, 259.9500122, 260.0, 260.6499939, 269.9700012, 274.8500061, 280.0, 284.9700012, 293.0400085, 297.0, 299.8500061, 299.9500122, 299.9700012, 299.980011, 299.9899902, 300.0, 319.9599915, 320.0, 325.0, 327.75, 329.9899902, 349.9899902, 350.0, 357.1000061, 359.9599915, 379.9599915, 396.0, 399.7999878, 399.9500122, 399.9599915, 399.980011, 399.9899902, 400.0, 449.9500122, 452.0400085, 461.480011, 474.9500122, 495.0, 499.75, 499.9500122, 500.0, 532.5800171, 599.9899902, 999.9899902, 1500.0, 1999.98999]

Column: order_region [23]
Unique values: ['Canada', 'Caribbean', 'Central Africa', 'Central America', 'Central Asia', 'East Africa', 'East of USA', 'Eastern Asia', 'Eastern Europe', 'North Africa', 'Northern Europe', 'Oceania', 'South America', 'South Asia', 'South of  USA ', 'Southeast Asia', 'Southern Africa', 'Southern Europe', 'US Center ', 'West Africa', 'West Asia', 'West of USA ', 'Western Europe']

Column: order_status [9]
Unique values: ['CANCELED', 'CLOSED', 'COMPLETE', 'ON_HOLD', 'PAYMENT_REVIEW', 'PENDING', 'PENDING_PAYMENT', 'PROCESSING', 'SUSPECTED_FRAUD']

Column: product_card_id [118]
Unique values: [19, 24, 35, 37, 44, 58, 60, 61, 78, 93, 116, 127, 134, 135, 172, 191, 203, 208, 216, 226, 235, 249, 251, 258, 273, 276, 278, 282, 295, 303, 305, 306, 311, 359, 364, 365, 403, 502, 564, 565, 567, 572, 607, 625, 627, 642, 646, 647, 652, 666, 671, 677, 691, 703, 705, 715, 724, 725, 728, 730, 743, 768, 771, 773, 775, 777, 778, 786, 792, 793, 797, 804, 810, 818, 821, 822, 823, 825, 828, 835, 845, 858, 860, 885, 886, 893, 897, 905, 906, 917, 924, 926, 957, 977, 981, 982, 1004, 1014, 1059, 1073, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 1362, 1363]

Column: product_category_id [51]
Unique values: [2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 16, 17, 18, 24, 26, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 40, 41, 43, 44, 45, 46, 48, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76]

Column: product_desc [1]
Unique values: [None]

Column: product_image [118]

In [ ]:
def count_nulls(df: pl.DataFrame) -> pl.DataFrame:
    return pl.DataFrame({
        "feature": df.columns,
        "null_count": df.null_count().row(0)
    })

pl.Config.set_tbl_rows(35)

null_counts = count_nulls(df)

pl.Config.set_tbl_rows(250)
null_counts

shape: (53, 2)
┌──────────────────────────┬────────────┐
│ feature                  ┆ null_count │
│ ---                      ┆ ---        │
│ str                      ┆ i64        │
╞══════════════════════════╪════════════╡
│ transaction_type         ┆ 0          │
│ actual_days_to_ship      ┆ 0          │
│ scheduled_days_to_ship   ┆ 0          │
│ benefit_per_order        ┆ 0          │
│ sales_per_customer       ┆ 0          │
│ delivery_status          ┆ 0          │
│ late_delivery_risk       ┆ 0          │
│ category_id              ┆ 0          │
│ category_name            ┆ 0          │
│ customer_city            ┆ 0          │
│ customer_country         ┆ 0          │
│ customer_email           ┆ 0          │
│ customer_fname           ┆ 0          │
│ customer_id              ┆ 0          │
│ customer_lname           ┆ 8          │
│ customer_password        ┆ 0          │
│ customer_segment         ┆ 0          │
│ customer_state           ┆ 0          │
│ customer_street          ┆ 0          │
│ customer_zipcode         ┆ 3          │
│ department_id            ┆ 0          │
│ department_name          ┆ 0          │
│ latitude                 ┆ 0          │
│ longitude                ┆ 0          │
│ market                   ┆ 0          │
│ order_city               ┆ 0          │
│ order_country            ┆ 0          │
│ order_customer_id        ┆ 0          │
│ order_date               ┆ 0          │
│ order_id                 ┆ 0          │
│ order_item_cardprod_id   ┆ 0          │
│ order_Item_discount      ┆ 0          │
│ order_item_discount_rate ┆ 0          │
│ order_item_id            ┆ 0          │
│ order_item_product_price ┆ 0          │
│ order_item_profit_ratio  ┆ 0          │
│ order_item_quantity      ┆ 0          │
│ sales                    ┆ 0          │
│ order_item_total         ┆ 0          │
│ order_profit_per_order   ┆ 0          │
│ order_region             ┆ 0          │
│ order_state              ┆ 0          │
│ order_status             ┆ 0          │
│ order_zipcode            ┆ 155679     │
│ product_card_id          ┆ 0          │
│ product_category_id      ┆ 0          │
│ product_desc             ┆ 180519     │
│ product_image            ┆ 0          │
│ product_name             ┆ 0          │
│ product_price            ┆ 0          │
│ product_status           ┆ 0          │
│ shipping_date            ┆ 0          │
│ shipping_mode            ┆ 0          │
└──────────────────────────┴────────────┘