In [2]:
import pandas as pd

In [4]:
df = pd.read_csv(
    "../data/data.csv", 
    engine='c'
    )

df

/var/folders/93/v_c2ph_17t97zdkzc4_ccjtw0000gn/T/ipykernel_18002/1482257344.py:1: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

,date_received,product,sub_product,issue,sub_issue,consumer_complaint_narrative,company_public_response,company,state_name,zip_code,tags,consumer_consent_provided,submitted_via,date_sent_to_company,company_response_to_consumer,timely_response,consumer_disputed,complaint_id
0,2019-06-13,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,NaN,CAPITAL ONE FINANCIAL CORPORATION,PA,18640.0,NaN,Consent not provided,Web,2019-06-13,Closed with explanation,Yes,NaN,3274605
1,2019-11-01,Vehicle loan or lease,Loan,Struggling to pay your loan,Denied request to lower payments,I contacted Ally on Friday XX/XX/XXXX after fa...,Company has responded to the consumer and the ...,ALLY FINANCIAL INC.,NJ,8854.0,NaN,Consent provided,Web,2019-11-01,Closed with explanation,Yes,NaN,3425257
2,2019-04-01,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Account status incorrect,NaN,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",PA,19067.0,NaN,Consent not provided,Web,2019-04-01,Closed with explanation,Yes,NaN,3198225
3,2019-04-10,Credit card or prepaid card,Store credit card,Closing your account,Can\'t close your account,NaN,Company believes it acted appropriately as aut...,Atlanticus Services Corporation,WI,54409.0,Older American,NaN,Referral,2019-04-16,Closed with explanation,No,NaN,3207424
4,2020-04-21,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Account information incorrect,Capital One Auto Finance incorrectly and witho...,NaN,CAPITAL ONE FINANCIAL CORPORATION,GA,30024.0,NaN,Consent provided,Web,2020-04-21,Closed with explanation,Yes,NaN,3616748
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
170124,2020-09-18,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,NaN,"EQUIFAX, INC.",CA,95136.0,NaN,Consent not provided,Web,2020-10-05,Closed with explanation,Yes,NaN,3854875
170125,2020-07-07,"Money transfer, virtual currency, or money ser...",Mobile or digital wallet,Unauthorized transactions or other transaction...,NaN,NaN,NaN,Square Inc.,NaN,NaN,NaN,NaN,Phone,2020-07-07,Closed with explanation,Yes,NaN,3733003
170126,2021-09-20,"Credit reporting, credit repair services, or o...",Credit reporting,Problem with a credit reporting company's inve...,Their investigation did not fix an error on yo...,NaN,NaN,"EQUIFAX, INC.",PA,15601.0,NaN,Other,Web,2021-09-20,Closed with explanation,Yes,NaN,4735927
170127,2019-12-02,Debt collection,I do not know,Attempts to collect debt not owed,Debt is not yours,This company appeared on my credit report out ...,NaN,"Synerprise Consulting Services, Inc.",MO,63137.0,NaN,Consent provided,Web,2019-12-02,Closed with explanation,Yes,NaN,3454681
170128,2020-04-25,Debt collection,I do not know,Attempts to collect debt not owed,Debt is not yours,NaN,NaN,"Credit Systems International, Inc.",TX,77433.0,NaN,Consent not provided,Web,2020-04-25,Closed with explanation,Yes,NaN,3622953

In [5]:
df.describe(include='all')

,date_received,product,sub_product,issue,sub_issue,consumer_complaint_narrative,company_public_response,company,state_name,zip_code,tags,consumer_consent_provided,submitted_via,date_sent_to_company,company_response_to_consumer,timely_response,consumer_disputed,complaint_id
count,170129,170129,169840,170129,149371,79349,84720,170129,166335,166304.0,21788,146532,170129,170129,170129,170129,1559,1.701290e+05
unique,2525,17,67,143,207,73166,11,2922,61,25081.0,3,4,6,2489,8,2,2,NaN
top,2021-06-09,"Credit reporting, credit repair services, or o...",Credit reporting,Incorrect information on your report,Information belongs to someone else,I am a victim of identity theft. The following...,Company has responded to the consumer and the ...,"EQUIFAX, INC.",CA,2301.0,Servicemember,Consent provided,Web,2021-06-09,Closed with explanation,Yes,No,NaN
freq,970,89652,88443,56139,36115,184,74532,27889,21353,245.0,13349,79359,148038,933,143425,167638,1226,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.696425e+06
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.708513e+05
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.454000e+03
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.297341e+06
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.525961e+06
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.286683e+06
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.028430e+06

In [6]:
df['complaint_id'].max()

5028430

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2396033 entries, 0 to 2396032
Data columns (total 18 columns):
 #   Column                        Dtype
---  ------                        -----
 0   date_received                 object
 1   product                       object
 2   sub_product                   object
 3   issue                         object
 4   sub_issue                     object
 5   consumer_complaint_narrative  object
 6   company_public_response       object
 7   company                       object
 8   state_name                    object
 9   zip_code                      object
 10  tags                          object
 11  consumer_consent_provided     object
 12  submitted_via                 object
 13  date_sent_to_company          object
 14  company_response_to_consumer  object
 15  timely_response               object
 16  consumer_disputed             object
 17  complaint_id                  int64
dtypes: int64(1), object(17)
memory usage: 329.0+ MB

In [9]:
for col in df.columns:
    print(f"{col}: {df[col].isnull().sum()}")

date_received: 0
product: 0
sub_product: 235164
issue: 0
sub_issue: 641100
consumer_complaint_narrative: 1560823
company_public_response: 1414645
company: 0
state_name: 38502
zip_code: 38719
tags: 2105561
consumer_consent_provided: 734001
submitted_via: 0
date_sent_to_company: 0
company_response_to_consumer: 3
timely_response: 0
consumer_disputed: 1627574
complaint_id: 0

In [5]:
for col in df.columns:
    if df[col].nunique() < 101:
        print(f"{col}: {df[col].unique()}")

product: ['Credit reporting, credit repair services, or other personal consumer reports'
 'Vehicle loan or lease' 'Credit card or prepaid card' 'Debt collection'
 'Mortgage' 'Checking or savings account'
 'Money transfer, virtual currency, or money service' 'Student loan'
 'Payday loan, title loan, or personal loan' 'Consumer Loan'
 'Bank account or service' 'Money transfers' 'Credit reporting'
 'Credit card' 'Other financial service' 'Payday loan' 'Prepaid card'
 'Virtual currency']
sub_product: ['Credit reporting' 'Loan' 'Store credit card' 'Credit card debt'
 'Conventional home mortgage' 'Checking account'
 'General-purpose prepaid card' 'Other personal consumer report'
 'General-purpose credit card or charge card'
 'Domestic (US) money transfer' 'Private student loan' 'Installment loan'
 'Lease' 'Personal line of credit' 'Other debt' 'FHA mortgage'
 'Medical debt' 'VA mortgage' 'Other banking product or service'
 'Payday loan debt' 'Other mortgage' 'Savings account'
 'International money transfer' 'Federal student loan servicing'
 'I do not know' 'Other type of mortgage' 'Private student loan debt'
 'Federal student loan debt' 'Credit card' 'CD (Certificate of Deposit)'
 'Mobile or digital wallet' 'Payday loan' 'Auto debt' 'Reverse mortgage'
 'Other bank product/service' 'Mortgage debt'
 'Other (i.e. phone, health club, etc.)' 'Conventional fixed mortgage'
 'Credit repair services' 'Home equity loan or line of credit (HELOC)'
 'Title loan' 'Auto' 'Non-federal student loan'
 "Traveler's check or cashier's check" 'Government benefit card' nan
 'Virtual currency' 'Check cashing service' 'Money order'
 'Debt settlement' 'Foreign currency exchange'
 'Home equity loan or line of credit' 'Medical' 'Mortgage' 'Vehicle loan'
 'Gift card' 'Conventional adjustable mortgage (ARM)'
 'Refund anticipation check' 'Payroll card' 'Vehicle lease' 'Pawn loan'
 'Credit repair' '(CD) Certificate of deposit'
 'Government benefit payment card' 'General purpose card'
 'Second mortgage' 'Other special purpose card' 'Check cashing'
 'Cashing a check without an account' 'Federal student loan'
 'Mobile wallet' 'Student prepaid card' 'ID prepaid card'
 'Gift or merchant card' 'Traveler’s/Cashier’s checks'
 'Electronic Benefit Transfer / EBT card' 'Transit card']
company_public_response: [nan
 'Company has responded to the consumer and the CFPB and chooses not to provide a public response'
 'Company believes it acted appropriately as authorized by contract or law'
 'Company disputes the facts presented in the complaint'
 'Company believes the complaint is the result of a misunderstanding'
 "Company can't verify or dispute the facts in the complaint"
 'Company believes complaint caused principally by actions of third party outside the control or direction of the company'
 'Company believes complaint is the result of an isolated error'
 'Company chooses not to provide a public response'
 'Company believes complaint represents an opportunity for improvement to better serve consumers'
 'Company believes complaint relates to a discontinued policy or procedure'
 "Company believes the complaint provided an opportunity to answer consumer's questions"]
state_name: ['PA' 'NJ' 'WI' 'GA' 'ID' 'NY' 'MT' 'TX' 'CA' 'FL' 'CT' 'IL' 'MA' 'KY'
 'NC' 'MI' 'OH' 'VA' 'WA' 'AL' 'MD' 'AZ' 'RI' 'TN' 'LA' 'CO' 'OR' 'IA' nan
 'MO' 'IN' 'HI' 'NH' 'SC' 'NE' 'MS' 'MN' 'ME' 'NV' 'UT' 'DE' 'AR' 'KS'
 'VT' 'OK' 'DC' 'PR' 'WV' 'ND' 'NM' 'AP' 'AE' 'SD' 'WY' 'VI' 'GU' 'AK'
 'UNITED STATES MINOR OUTLYING ISLANDS' 'AA' 'AS' 'MP' 'FM' 'MH' 'PW']
tags: [nan 'Older American' 'Servicemember' 'Older American, Servicemember']
consumer_consent_provided: ['Consent not provided' 'Consent provided' nan 'Other' 'Consent withdrawn']
submitted_via: ['Web' 'Referral' 'Fax' 'Postal mail' 'Phone' 'Email']
company_response_to_consumer: ['Closed with explanation' 'In progress' 'Closed with monetary relief'
 'Closed with non-monetary relief' 'Untimely response' 'Closed'
 'Closed with relief' 'Closed without relief' nan]
timely_response: ['Yes' 'No']
consumer_disputed: [nan 'No' 'Yes']

In [8]:
df.nunique()

date_received                      3675
product                              18
sub_product                          76
issue                               165
sub_issue                           221
consumer_complaint_narrative     748939
company_public_response              11
company                            6236
state_name                           63
zip_code                          58013
tags                                  3
consumer_consent_provided             4
submitted_via                         6
date_sent_to_company               3624
company_response_to_consumer          8
timely_response                       2
consumer_disputed                     2
complaint_id                    2396033
dtype: int64

### Retrieve Longest String Value For Non-Numeric Columns

In [9]:
def longest_string_length(df):
    # Select non-numeric columns
    non_numeric_cols = df.select_dtypes(exclude=['number', 'bool'])
    # Calculate the length of the longest string for each column
    return non_numeric_cols.apply(lambda col: col.dropna().astype(str).map(len).max())

# Get the result
longest_lengths = longest_string_length(df)

print(longest_lengths)

date_received                      10
product                            76
sub_product                        42
issue                              80
sub_issue                          85
consumer_complaint_narrative    32317
company_public_response           119
company                            88
state_name                         36
zip_code                            7
tags                               29
consumer_consent_provided          20
submitted_via                      11
date_sent_to_company               10
company_response_to_consumer       31
timely_response                     3
consumer_disputed                   3
dtype: int64